// Pre-built control test templates for automated compliance testing
// Reduces onboarding from weeks to hours — 30+ ready-to-run tests mapped to frameworks

export const testTemplateCategories = {
  access_control: { label: "Access Control", color: "text-blue-600 bg-blue-50" },
  data_protection: { label: "Data Protection", color: "text-emerald-600 bg-emerald-50" },
  network_security: { label: "Network Security", color: "text-cyan-600 bg-cyan-50" },
  incident_response: { label: "Incident Response", color: "text-red-600 bg-red-50" },
  change_management: { label: "Change Management", color: "text-purple-600 bg-purple-50" },
  security_operations: { label: "Security Operations", color: "text-orange-600 bg-orange-50" },
  human_resources: { label: "Human Resources", color: "text-pink-600 bg-pink-50" },
  asset_management: { label: "Asset Management", color: "text-amber-600 bg-amber-50" },
};

export const controlTestTemplates = [
  // Access Control
  {
    id: "mfa-enforced-all-users",
    title: "MFA Enforced for All Users",
    category: "access_control",
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "POPIA", "GDPR"],
    description: "Verifies that multi-factor authentication is enforced for 100% of active user accounts.",
    passCriteria: "100% of active users have MFA enabled",
    failCriteria: "Any active user without MFA enrolled",
    automationLevel: "automated",
    evidenceType: "API export / Configuration screenshot",
    integration: "okta",
    severity: "critical",
  },
  {
    id: "inactive-users-disabled-90",
    title: "Inactive Users Disabled After 90 Days",
    category: "access_control",
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
    description: "Checks that user accounts inactive for 90+ days are disabled or removed.",
    passCriteria: "No active users with last login >90 days ago",
    failCriteria: "Any active user with last login >90 days ago",
    automationLevel: "automated",
    evidenceType: "Directory export",
    integration: "okta",
    severity: "high",
  },
  {
    id: "privileged-access-reviewed-quarterly",
    title: "Privileged Access Reviewed Quarterly",
    category: "access_control",
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "King V"],
    description: "Verifies that privileged/admin accounts are reviewed every quarter with sign-off.",
    passCriteria: "100% of privileged accounts reviewed in current quarter",
    failCriteria: "Any privileged account without quarterly review record",
    automationLevel: "partially_automated",
    evidenceType: "Access review report + sign-off",
    integration: null,
    severity: "high",
  },
  {
    id: "sso-required-saas",
    title: "SSO Required for SaaS Applications",
    category: "access_control",
    frameworks: ["SOC 2", "ISO 27001"],
    description: "Checks that all production SaaS apps enforce SSO authentication (no local passwords).",
    passCriteria: "All SaaS apps configured for SSO/SAML",
    failCriteria: "Any SaaS app allowing password-only login",
    automationLevel: "manual",
    evidenceType: "SaaS inventory + SSO config screenshots",
    integration: null,
    severity: "medium",
  },
  {
    id: "least-privilege-enforced",
    title: "Least Privilege Access Enforced",
    category: "access_control",
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
    description: "Verifies that users have only the minimum permissions required for their role.",
    passCriteria: "All user roles map to documented least-privilege matrix",
    failCriteria: "Any user with permissions exceeding their role matrix",
    automationLevel: "partially_automated",
    evidenceType: "Role-permission matrix + IAM export",
    integration: "aws",
    severity: "high",
  },
  // Data Protection
  {
    id: "encryption-at-rest-enabled",
    title: "Encryption at Rest Enabled",
    category: "data_protection",
    frameworks: ["SOC 2", "ISO 27001", "PCI DSS", "POPIA", "GDPR"],
    description: "Verifies that encryption at rest is enabled on all databases, storage, and backups.",
    passCriteria: "100% of data stores have encryption at rest enabled",
    failCriteria: "Any data store without encryption at rest",
    automationLevel: "automated",
    evidenceType: "Cloud config export",
    integration: "aws",
    severity: "critical",
  },
  {
    id: "encryption-in-transit-tls",
    title: "TLS 1.2+ for All Traffic (Encryption in Transit)",
    category: "data_protection",
    frameworks: ["SOC 2", "ISO 27001", "PCI DSS", "POPIA"],
    description: "Verifies that all external endpoints enforce TLS 1.2 or higher.",
    passCriteria: "All public endpoints enforce TLS 1.2+",
    failCriteria: "Any endpoint allowing TLS 1.0/1.1 or plaintext",
    automationLevel: "automated",
    evidenceType: "SSL Labs scan report",
    integration: "cloudflare",
    severity: "critical",
  },
  {
    id: "data-classification-applied",
    title: "Data Classification Labels Applied",
    category: "data_protection",
    frameworks: ["ISO 27001", "POPIA", "GDPR"],
    description: "Verifies that data assets are classified (Public, Internal, Confidential, Restricted).",
    passCriteria: "All data assets have classification labels",
    failCriteria: "Any unclassified data store containing PII",
    automationLevel: "manual",
    evidenceType: "Data asset register",
    integration: null,
    severity: "medium",
  },
  {
    id: "backup-encryption-verified",
    title: "Backups Encrypted and Tested",
    category: "data_protection",
    frameworks: ["SOC 2", "ISO 27001"],
    description: "Verifies that backups are encrypted and a restore test was performed in the last quarter.",
    passCriteria: "Backups encrypted + restore test completed in current quarter",
    failCriteria: "Unencrypted backups or no restore test in 90 days",
    automationLevel: "manual",
    evidenceType: "Backup config + restore test report",
    integration: null,
    severity: "high",
  },
  // Network Security
  {
    id: "no-public-s3-buckets",
    title: "No Public S3 / Storage Buckets",
    category: "network_security",
    frameworks: ["SOC 2", "ISO 27001", "PCI DSS"],
    description: "Scans for publicly accessible cloud storage buckets.",
    passCriteria: "0 public-read or public-write storage buckets",
    failCriteria: "Any publicly accessible storage bucket",
    automationLevel: "automated",
    evidenceType: "Cloud security scan",
    integration: "aws",
    severity: "critical",
  },
  {
    id: "waf-enabled-production",
    title: "WAF Enabled for Production Endpoints",
    category: "network_security",
    frameworks: ["SOC 2", "PCI DSS"],
    description: "Verifies that a Web Application Firewall protects all production endpoints.",
    passCriteria: "WAF enabled in block mode for all production domains",
    failCriteria: "Any production domain without WAF or WAF in detect-only mode",
    automationLevel: "automated",
    evidenceType: "WAF config export",
    integration: "cloudflare",
    severity: "high",
  },
  {
    id: "firewall-rules-reviewed",
    title: "Firewall / Security Group Rules Reviewed Quarterly",
    category: "network_security",
    frameworks: ["SOC 2", "ISO 27001", "PCI DSS"],
    description: "Verifies that firewall and security group rules are reviewed quarterly.",
    passCriteria: "All firewall rules reviewed and signed off in current quarter",
    failCriteria: "Any unreviewed firewall rules",
    automationLevel: "partially_automated",
    evidenceType: "Firewall rule export + review sign-off",
    integration: "aws",
    severity: "medium",
  },
  {
    id: "dnssec-enabled",
    title: "DNSSEC Enabled on All Domains",
    category: "network_security",
    frameworks: ["ISO 27001", "NIST CSF"],
    description: "Verifies that DNSSEC is enabled on all owned domains.",
    passCriteria: "DNSSEC enabled on 100% of domains",
    failCriteria: "Any domain without DNSSEC",
    automationLevel: "automated",
    evidenceType: "DNS config export",
    integration: "cloudflare",
    severity: "low",
  },
  // Incident Response
  {
    id: "ir-plan-documented",
    title: "Incident Response Plan Documented",
    category: "incident_response",
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "POPIA"],
    description: "Verifies that a documented IR plan exists and was updated in the last 12 months.",
    passCriteria: "IR plan exists, reviewed/updated within 12 months",
    failCriteria: "No IR plan or plan >12 months old",
    automationLevel: "manual",
    evidenceType: "IR plan document with version date",
    integration: null,
    severity: "high",
  },
  {
    id: "on-call-schedule-active",
    title: "On-Call Schedule Active 24/7",
    category: "incident_response",
    frameworks: ["SOC 2", "ISO 27001"],
    description: "Verifies that a 24/7 on-call schedule is active with escalation policies.",
    passCriteria: "Active on-call schedule covering all hours with escalation",
    failCriteria: "Gaps in on-call coverage or no escalation policy",
    automationLevel: "automated",
    evidenceType: "On-call schedule export",
    integration: "pagerduty",
    severity: "high",
  },
  {
    id: "post-incident-reviews",
    title: "Post-Incident Reviews Completed for All Incidents",
    category: "incident_response",
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
    description: "Verifies that all incidents in the last quarter have a completed post-incident review.",
    passCriteria: "100% of incidents have post-incident review documented",
    failCriteria: "Any incident without a post-incident review",
    automationLevel: "manual",
    evidenceType: "Post-incident review documents",
    integration: null,
    severity: "medium",
  },
  {
    id: "incident-response-time-sla",
    title: "Incident Response Time Within SLA",
    category: "incident_response",
    frameworks: ["SOC 2", "ISO 27001"],
    description: "Verifies that critical incidents are acknowledged within the defined SLA (e.g., 15 min).",
    passCriteria: "100% of critical incidents acknowledged within SLA",
    failCriteria: "Any critical incident exceeding response SLA",
    automationLevel: "automated",
    evidenceType: "Incident metrics export",
    integration: "pagerduty",
    severity: "high",
  },
  // Change Management
  {
    id: "code-review-required",
    title: "Code Review Required for All Merges",
    category: "change_management",
    frameworks: ["SOC 2", "ISO 27001"],
    description: "Verifies that all code merges to production require at least one approval.",
    passCriteria: "100% of production merges have code review approval",
    failCriteria: "Any direct push to production without review",
    automationLevel: "automated",
    evidenceType: "Repository settings + merge history",
    integration: "github",
    severity: "high",
  },
  {
    id: "deployment-approval-required",
    title: "Deployment Approvals Required for Production",
    category: "change_management",
    frameworks: ["SOC 2", "ISO 27001"],
    description: "Verifies that production deployments require explicit approval.",
    passCriteria: "All production deployments have approval records",
    failCriteria: "Any unapproved production deployment",
    automationLevel: "partially_automated",
    evidenceType: "CI/CD pipeline config + deployment logs",
    integration: "github",
    severity: "high",
  },
  {
    id: "rollback-procedure-documented",
    title: "Rollback Procedure Documented and Tested",
    category: "change_management",
    frameworks: ["SOC 2", "ISO 27001"],
    description: "Verifies that a rollback procedure exists and was tested in the last 6 months.",
    passCriteria: "Rollback procedure documented + tested within 6 months",
    failCriteria: "No rollback procedure or no test in 6 months",
    automationLevel: "manual",
    evidenceType: "Rollback procedure document + test record",
    integration: null,
    severity: "medium",
  },
  // Security Operations
  {
    id: "log-retention-365",
    title: "Security Logs Retained for 365 Days",
    category: "security_operations",
    frameworks: ["SOC 2", "ISO 27001", "PCI DSS"],
    description: "Verifies that security logs are retained for at least 365 days.",
    passCriteria: "Log retention configured for 365+ days",
    failCriteria: "Log retention <365 days",
    automationLevel: "automated",
    evidenceType: "Log management config",
    integration: "datadog",
    severity: "high",
  },
  {
    id: "vulnerability-scanning-weekly",
    title: "Vulnerability Scans Run Weekly",
    category: "security_operations",
    frameworks: ["SOC 2", "ISO 27001", "PCI DSS"],
    description: "Verifies that vulnerability scans run at least weekly with no critical findings unaddressed.",
    passCriteria: "Weekly scans running + 0 open critical vulnerabilities >30 days",
    failCriteria: "Scans not weekly or critical vulns open >30 days",
    automationLevel: "automated",
    evidenceType: "Vulnerability scan reports",
    integration: "aws",
    severity: "high",
  },
  {
    id: "patching-sla-critical",
    title: "Critical Patches Applied Within 7 Days",
    category: "security_operations",
    frameworks: ["SOC 2", "ISO 27001", "PCI DSS"],
    description: "Verifies that critical security patches are applied within 7 days of release.",
    passCriteria: "100% of critical patches applied within 7 days",
    failCriteria: "Any critical patch open >7 days",
    automationLevel: "partially_automated",
    evidenceType: "Patch management report",
    integration: null,
    severity: "critical",
  },
  {
    id: "siem-alerting-active",
    title: "SIEM Alerting Active for Critical Events",
    category: "security_operations",
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
    description: "Verifies that SIEM alerts are configured for critical security events.",
    passCriteria: "Active SIEM alerts for all critical event types",
    failCriteria: "Missing alerts for any critical event type",
    automationLevel: "automated",
    evidenceType: "SIEM alert configuration export",
    integration: "datadog",
    severity: "high",
  },
  // Human Resources
  {
    id: "background-checks-completed",
    title: "Background Checks Completed Before Start Date",
    category: "human_resources",
    frameworks: ["SOC 2", "ISO 27001"],
    description: "Verifies that background checks are completed for all new hires before their start date.",
    passCriteria: "100% of new hires have completed background checks",
    failCriteria: "Any new hire without a completed background check",
    automationLevel: "manual",
    evidenceType: "HR records / background check confirmations",
    integration: null,
    severity: "medium",
  },
  {
    id: "security-training-annual",
    title: "Security Awareness Training Completed Annually",
    category: "human_resources",
    frameworks: ["SOC 2", "ISO 27001", "POPIA"],
    description: "Verifies that all employees completed security awareness training in the last 12 months.",
    passCriteria: "100% of employees completed training in last 12 months",
    failCriteria: "Any employee without completed training in 12 months",
    automationLevel: "partially_automated",
    evidenceType: "Training completion records",
    integration: null,
    severity: "high",
  },
  {
    id: "policy-acknowledgments-current",
    title: "Policy Acknowledgments Current for All Staff",
    category: "human_resources",
    frameworks: ["SOC 2", "ISO 27001", "POPIA"],
    description: "Verifies that all employees have signed current versions of key policies.",
    passCriteria: "100% of employees have signed all current policies",
    failCriteria: "Any employee with missing or outdated policy acknowledgment",
    automationLevel: "automated",
    evidenceType: "Policy attestation records",
    integration: null,
    severity: "high",
  },
  // Asset Management
  {
    id: "asset-inventory-current",
    title: "Asset Inventory Current and Reviewed",
    category: "asset_management",
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
    description: "Verifies that the asset inventory is current and reviewed quarterly.",
    passCriteria: "Asset inventory updated and reviewed in current quarter",
    failCriteria: "Asset inventory >90 days old or incomplete",
    automationLevel: "manual",
    evidenceType: "Asset inventory export + review sign-off",
    integration: null,
    severity: "medium",
  },
  {
    id: "endpoint-protection-deployed",
    title: "Endpoint Protection Deployed on All Devices",
    category: "asset_management",
    frameworks: ["SOC 2", "ISO 27001"],
    description: "Verifies that endpoint protection (EDR/AV) is deployed on all company devices.",
    passCriteria: "100% of enrolled devices have active EDR/AV",
    failCriteria: "Any enrolled device without active EDR/AV",
    automationLevel: "automated",
    evidenceType: "MDM/EDR dashboard export",
    integration: null,
    severity: "high",
  },
  {
    id: "encryption-full-disk-enabled",
    title: "Full Disk Encryption Enabled on All Laptops",
    category: "asset_management",
    frameworks: ["SOC 2", "ISO 27001", "POPIA"],
    description: "Verifies that full disk encryption (FileVault/BitLocker) is enabled on all laptops.",
    passCriteria: "100% of laptops have full disk encryption enabled",
    failCriteria: "Any laptop without full disk encryption",
    automationLevel: "automated",
    evidenceType: "MDM compliance report",
    integration: null,
    severity: "high",
  },
];

export const getTemplatesByCategory = () => {
  const grouped = {};
  for (const [key, val] of Object.entries(testTemplateCategories)) {
    grouped[key] = { ...val, items: controlTestTemplates.filter((t) => t.category === key) };
  }
  return grouped;
};

export const getTemplatesByFramework = (framework) =>
  controlTestTemplates.filter((t) => t.frameworks.includes(framework));