// Authoritative pre-built control libraries for one-click import.
// Each control: { control_id, title, category, description }
// category must match the Control entity enum.

export const CONTROL_LIBRARIES = [
  {
    key: "iso27001_2022",
    name: "ISO 27001:2022",
    version: "2022",
    description: "Information security management system — Annex A controls (93).",
    controls: [
      // A.5 Organizational (37)
      { control_id: "A.5.1", title: "Policies for information security", category: "compliance", description: "Author and approve information security policies." },
      { control_id: "A.5.2", title: "Information security roles and responsibilities", category: "access_control", description: "Allocate roles and responsibilities for security." },
      { control_id: "A.5.3", title: "Segregation of duties", category: "access_control", description: "Separate conflicting duties to reduce risk." },
      { control_id: "A.5.4", title: "Management responsibilities", category: "compliance", description: "Ensure personnel apply information security." },
      { control_id: "A.5.5", title: "Contact with authorities", category: "compliance", description: "Maintain contact with relevant authorities." },
      { control_id: "A.5.6", title: "Contact with special interest groups", category: "compliance", description: "Maintain contact with special interest groups." },
      { control_id: "A.5.7", title: "Threat intelligence", category: "risk_management", description: "Collect and use threat intelligence." },
      { control_id: "A.5.8", title: "Information security in project management", category: "compliance", description: "Integrate security into project management." },
      { control_id: "A.5.9", title: "Inventory of information and other associated assets", category: "asset_management", description: "Maintain an inventory of assets." },
      { control_id: "A.5.10", title: "Acceptable use of information and other associated assets", category: "compliance", description: "Define acceptable use of assets." },
      { control_id: "A.5.11", title: "Return of assets", category: "asset_management", description: "Return assets upon termination." },
      { control_id: "A.5.12", title: "Classification of information", category: "data_protection", description: "Classify information by sensitivity." },
      { control_id: "A.5.13", title: "Labelling of information", category: "data_protection", description: "Label information per classification." },
      { control_id: "A.5.14", title: "Information transfer", category: "data_protection", description: "Protect information in transfer." },
      { control_id: "A.5.15", title: "Access control", category: "access_control", description: "Define access control rules." },
      { control_id: "A.5.16", title: "Identity management", category: "access_control", description: "Manage identities lifecycle." },
      { control_id: "A.5.17", title: "Authentication information", category: "access_control", description: "Manage authentication information." },
      { control_id: "A.5.18", title: "Access rights", category: "access_control", description: "Grant and revoke access rights." },
      { control_id: "A.5.19", title: "Information security in supplier relationships", category: "compliance", description: "Define supplier security requirements." },
      { control_id: "A.5.20", title: "Addressing information security within supplier agreements", category: "compliance", description: "Include security in supplier agreements." },
      { control_id: "A.5.21", title: "Managing information security in the ICT supply chain", category: "compliance", description: "Manage ICT supply chain risk." },
      { control_id: "A.5.22", title: "Monitoring, review and change management of supplier services", category: "compliance", description: "Monitor and review supplier services." },
      { control_id: "A.5.23", title: "Information security for use of cloud services", category: "compliance", description: "Define security for cloud services." },
      { control_id: "A.5.24", title: "Information security incident management planning and preparation", category: "incident_response", description: "Plan and prepare for incidents." },
      { control_id: "A.5.25", title: "Assessment and decision on information security events", category: "incident_response", description: "Assess security events." },
      { control_id: "A.5.26", title: "Response to information security incidents", category: "incident_response", description: "Respond to incidents." },
      { control_id: "A.5.27", title: "Learning from information security incidents", category: "incident_response", description: "Learn from incidents." },
      { control_id: "A.5.28", title: "Collection of evidence", category: "incident_response", description: "Collect and preserve evidence." },
      { control_id: "A.5.29", title: "Information security during disruption", category: "business_continuity", description: "Maintain security during disruptions." },
      { control_id: "A.5.30", title: "ICT readiness for business continuity", category: "business_continuity", description: "Ensure ICT readiness for continuity." },
      { control_id: "A.5.31", title: "Legal, statutory, regulatory and contractual requirements", category: "compliance", description: "Identify and meet legal requirements." },
      { control_id: "A.5.32", title: "Intellectual property rights", category: "compliance", description: "Protect intellectual property rights." },
      { control_id: "A.5.33", title: "Protection of records", category: "compliance", description: "Protect records from loss/theft/damage." },
      { control_id: "A.5.34", title: "Privacy and protection of PII", category: "compliance", description: "Protect personal data." },
      { control_id: "A.5.35", title: "Independent review of information security", category: "compliance", description: "Independently review security." },
      { control_id: "A.5.36", title: "Compliance with policies, rules and standards", category: "compliance", description: "Ensure compliance with policies." },
      { control_id: "A.5.37", title: "Documented operating procedures", category: "compliance", description: "Document operating procedures." },
      // A.6 People (8)
      { control_id: "A.6.1", title: "Screening", category: "human_resources", description: "Screen personnel before employment." },
      { control_id: "A.6.2", title: "Terms and conditions of employment", category: "human_resources", description: "Include security in employment terms." },
      { control_id: "A.6.3", title: "Information security awareness, education and training", category: "human_resources", description: "Provide security awareness training." },
      { control_id: "A.6.4", title: "Disciplinary process", category: "human_resources", description: "Apply disciplinary process for breaches." },
      { control_id: "A.6.5", title: "Responsibilities after termination or change of employment", category: "human_resources", description: "Define post-termination responsibilities." },
      { control_id: "A.6.6", title: "Confidentiality or non-disclosure agreements", category: "human_resources", description: "Sign confidentiality agreements." },
      { control_id: "A.6.7", title: "Remote working", category: "human_resources", description: "Secure remote working." },
      { control_id: "A.6.8", title: "Information security event reporting", category: "incident_response", description: "Report security events." },
      // A.7 Physical (14)
      { control_id: "A.7.1", title: "Physical security perimeters", category: "physical_security", description: "Define physical security perimeters." },
      { control_id: "A.7.2", title: "Physical entry", category: "physical_security", description: "Control physical entry." },
      { control_id: "A.7.3", title: "Securing offices, rooms and facilities", category: "physical_security", description: "Secure offices and facilities." },
      { control_id: "A.7.4", title: "Physical security monitoring", category: "physical_security", description: "Monitor physical security." },
      { control_id: "A.7.5", title: "Protecting against physical and environmental threats", category: "physical_security", description: "Protect against environmental threats." },
      { control_id: "A.7.6", title: "Working in secure areas", category: "physical_security", description: "Define rules for secure areas." },
      { control_id: "A.7.7", title: "Clear desk and clear screen", category: "physical_security", description: "Enforce clear desk and screen." },
      { control_id: "A.7.8", title: "Equipment siting and protection", category: "physical_security", description: "Site and protect equipment." },
      { control_id: "A.7.9", title: "Security of assets off-premises", category: "physical_security", description: "Secure assets off-premises." },
      { control_id: "A.7.10", title: "Storage media", category: "physical_security", description: "Manage storage media." },
      { control_id: "A.7.11", title: "Supporting utilities", category: "physical_security", description: "Protect supporting utilities." },
      { control_id: "A.7.12", title: "Cabling security", category: "physical_security", description: "Secure cabling." },
      { control_id: "A.7.13", title: "Equipment maintenance", category: "physical_security", description: "Maintain equipment." },
      { control_id: "A.7.14", title: "Secure disposal or re-use of equipment", category: "physical_security", description: "Securely dispose or reuse equipment." },
      // A.8 Technological (34)
      { control_id: "A.8.1", title: "User endpoint devices", category: "access_control", description: "Secure user endpoint devices." },
      { control_id: "A.8.2", title: "Privileged access rights", category: "access_control", description: "Manage privileged access rights." },
      { control_id: "A.8.3", title: "Information access restriction", category: "access_control", description: "Restrict access to information." },
      { control_id: "A.8.4", title: "Access to source code", category: "access_control", description: "Control access to source code." },
      { control_id: "A.8.5", title: "Secure authentication", category: "access_control", description: "Implement secure authentication." },
      { control_id: "A.8.6", title: "Capacity management", category: "security_operations", description: "Manage capacity." },
      { control_id: "A.8.7", title: "Protection against malware", category: "security_operations", description: "Protect against malware." },
      { control_id: "A.8.8", title: "Management of technical vulnerabilities", category: "security_operations", description: "Manage technical vulnerabilities." },
      { control_id: "A.8.9", title: "Configuration management", category: "change_management", description: "Manage configurations." },
      { control_id: "A.8.10", title: "Information deletion", category: "data_protection", description: "Securely delete information." },
      { control_id: "A.8.11", title: "Data masking", category: "data_protection", description: "Mask sensitive data." },
      { control_id: "A.8.12", title: "Data leakage prevention", category: "data_protection", description: "Prevent data leakage." },
      { control_id: "A.8.13", title: "Information backup", category: "data_protection", description: "Back up information." },
      { control_id: "A.8.14", title: "Redundancy of information processing facilities", category: "business_continuity", description: "Provide redundancy." },
      { control_id: "A.8.15", title: "Logging", category: "security_operations", description: "Log events." },
      { control_id: "A.8.16", title: "Monitoring activities", category: "security_operations", description: "Monitor systems." },
      { control_id: "A.8.17", title: "Clock synchronisation", category: "security_operations", description: "Synchronize clocks." },
      { control_id: "A.8.18", title: "Use of privileged utility programs", category: "access_control", description: "Restrict privileged utilities." },
      { control_id: "A.8.19", title: "Installation of software on operational systems", category: "change_management", description: "Control software installation." },
      { control_id: "A.8.20", title: "Networks security", category: "network_security", description: "Secure networks." },
      { control_id: "A.8.21", title: "Security of network services", category: "network_security", description: "Secure network services." },
      { control_id: "A.8.22", title: "Segregation of networks", category: "network_security", description: "Segregate networks." },
      { control_id: "A.8.23", title: "Web filtering", category: "network_security", description: "Filter web content." },
      { control_id: "A.8.24", title: "Use of cryptography", category: "data_protection", description: "Use cryptography appropriately." },
      { control_id: "A.8.25", title: "Secure development life cycle", category: "change_management", description: "Apply secure SDLC." },
      { control_id: "A.8.26", title: "Application security requirements", category: "compliance", description: "Define application security requirements." },
      { control_id: "A.8.27", title: "Secure system architecture and engineering", category: "security_operations", description: "Engineer secure architecture." },
      { control_id: "A.8.28", title: "Secure coding", category: "security_operations", description: "Apply secure coding." },
      { control_id: "A.8.29", title: "Security testing in development and acceptance", category: "security_operations", description: "Test security in dev and acceptance." },
      { control_id: "A.8.30", title: "Outsourced development", category: "compliance", description: "Secure outsourced development." },
      { control_id: "A.8.31", title: "Separation of development, test and production environments", category: "change_management", description: "Separate environments." },
      { control_id: "A.8.32", title: "Change management", category: "change_management", description: "Manage changes." },
      { control_id: "A.8.33", title: "Test information", category: "change_management", description: "Protect test information." },
      { control_id: "A.8.34", title: "Protection of information systems during audit testing", category: "compliance", description: "Protect systems during audits." }
    ]
  },
  {
    key: "soc2_tsc",
    name: "SOC 2 Trust Service Criteria",
    version: "2017",
    description: "AICPA Common Criteria (CC1–CC9) plus Availability, Processing Integrity, Confidentiality and Privacy.",
    controls: [
      { control_id: "CC1.1", title: "Demonstrate commitment to integrity and ethical values", category: "compliance", description: "Tone at the top." },
      { control_id: "CC1.2", title: "Exercise oversight responsibility", category: "compliance", description: "Board oversight of the system." },
      { control_id: "CC1.3", title: "Establish structure, authority and responsibility", category: "compliance", description: "Organizational structure." },
      { control_id: "CC1.4", title: "Demonstrate commitment to competence", category: "human_resources", description: "Competence of personnel." },
      { control_id: "CC1.5", title: "Enforce accountability", category: "compliance", description: "Accountability for controls." },
      { control_id: "CC2.1", title: "Obtain and use relevant, quality information", category: "compliance", description: "Information for internal control." },
      { control_id: "CC2.2", title: "Communicate internally", category: "compliance", description: "Internal communication of objectives." },
      { control_id: "CC2.3", title: "Communicate externally", category: "compliance", description: "External communication of objectives." },
      { control_id: "CC3.1", title: "Identify and assess risk", category: "risk_management", description: "Identify risks to objectives." },
      { control_id: "CC3.2", title: "Evaluate severity of risks", category: "risk_management", description: "Assess risk severity." },
      { control_id: "CC3.3", title: "Select and develop risk responses", category: "risk_management", description: "Risk responses." },
      { control_id: "CC3.4", title: "Assess changes in risk", category: "risk_management", description: "Assess changes impacting risk." },
      { control_id: "CC4.1", title: "Conduct ongoing and/or separate evaluations", category: "security_operations", description: "Monitoring of controls." },
      { control_id: "CC4.2", title: "Evaluate and communicate deficiencies", category: "security_operations", description: "Communicate deficiencies." },
      { control_id: "CC5.1", title: "Select and develop control activities", category: "security_operations", description: "Control activities." },
      { control_id: "CC5.2", title: "Select and develop general controls over technology", category: "security_operations", description: "IT general controls." },
      { control_id: "CC5.3", title: "Deploy controls through policies and procedures", category: "compliance", description: "Deploy control activities." },
      { control_id: "CC6.1", title: "Logical and physical access controls", category: "access_control", description: "Implement logical access security." },
      { control_id: "CC6.2", title: "Prior to access, identify and authenticate users", category: "access_control", description: "User identification and authentication." },
      { control_id: "CC6.3", title: "Authorize, modify and remove access", category: "access_control", description: "Access provisioning lifecycle." },
      { control_id: "CC6.4", title: "Restrict physical access", category: "physical_security", description: "Restrict physical access to facilities." },
      { control_id: "CC6.5", title: "Dispose of data and assets", category: "asset_management", description: "Secure disposal of data." },
      { control_id: "CC6.6", title: "External vendor and business partner access", category: "access_control", description: "Manage external access." },
      { control_id: "CC6.7", title: "Confidentiality and transmission of data", category: "data_protection", description: "Protect data in transit." },
      { control_id: "CC6.8", title: "Implement intrusion detection and prevention", category: "security_operations", description: "IDPS controls." },
      { control_id: "CC7.1", title: "Detect anomalies and security events", category: "security_operations", description: "Detect security events." },
      { control_id: "CC7.2", title: "Monitor system performance", category: "security_operations", description: "Monitor performance." },
      { control_id: "CC7.3", title: "Evaluate security events to determine incidents", category: "incident_response", description: "Evaluate events for incidents." },
      { control_id: "CC7.4", title: "Respond to and recover from incidents", category: "incident_response", description: "Incident response." },
      { control_id: "CC7.5", title: "Identify and recover from incidents", category: "incident_response", description: "Recover from incidents." },
      { control_id: "CC8.1", title: "Authorize, document, test and approve changes", category: "change_management", description: "Change management." },
      { control_id: "CC9.1", title: "Identify and manage risk of vendor disruptions", category: "risk_management", description: "Vendor risk mitigation." },
      { control_id: "CC9.2", title: "Develop business continuity and disaster recovery", category: "business_continuity", description: "BCDR planning." },
      { control_id: "A1.1", title: "Environmental protections for availability", category: "business_continuity", description: "Environmental protection." },
      { control_id: "A1.2", title: "Recover from disruptions", category: "business_continuity", description: "Availability recovery." },
      { control_id: "A1.3", title: "Backup and recovery of information", category: "data_protection", description: "Backups for availability." },
      { control_id: "PI1.1", title: "Validate processing integrity", category: "security_operations", description: "Processing integrity validation." },
      { control_id: "C1.1", title: "Confidentiality protections", category: "data_protection", description: "Protect confidential information." },
      { control_id: "P1.1", title: "Privacy notice and communication", category: "compliance", description: "Privacy notices." }
    ]
  },
  {
    key: "nist_csf_2",
    name: "NIST CSF 2.0",
    version: "2.0",
    description: "Functions: Govern, Identify, Protect, Detect, Respond, Recover with category-level controls.",
    controls: [
      { control_id: "GV.OC", title: "Organizational Context", category: "compliance", description: "Understand the organization and its context." },
      { control_id: "GV.RM", title: "Risk Management Strategy", category: "risk_management", description: "Establish and communicate risk strategy." },
      { control_id: "GV.RR", title: "Roles, Responsibilities and Authorities", category: "compliance", description: "Define cybersecurity roles and responsibilities." },
      { control_id: "GV.PO", title: "Policy", category: "compliance", description: "Establish and communicate cybersecurity policy." },
      { control_id: "GV.OV", title: "Oversight", category: "compliance", description: "Oversight of cybersecurity risk management." },
      { control_id: "GV.SC", title: "Cybersecurity Supply Chain Risk Management", category: "compliance", description: "Manage supply chain risk." },
      { control_id: "ID.AM", title: "Asset Management", category: "asset_management", description: "Inventory and manage assets." },
      { control_id: "ID.RA", title: "Risk Assessment", category: "risk_management", description: "Assess cybersecurity risk." },
      { control_id: "ID.IM", title: "Improvements", category: "risk_management", description: "Improvements from assessments and monitoring." },
      { control_id: "PR.AA", title: "Identity Management, Authentication and Access Control", category: "access_control", description: "Protect access to assets." },
      { control_id: "PR.AT", title: "Awareness and Training", category: "human_resources", description: "Provide awareness and training." },
      { control_id: "PR.DS", title: "Data Security", category: "data_protection", description: "Protect data." },
      { control_id: "PR.PS", title: "Platform Security", category: "security_operations", description: "Secure hardware, software and services." },
      { control_id: "DE.CM", title: "Continuous Monitoring", category: "security_operations", description: "Monitor for security events." },
      { control_id: "DE.AE", title: "Adverse Event Analysis", category: "security_operations", description: "Analyze adverse events." },
      { control_id: "RS.MA", title: "Incident Management", category: "incident_response", description: "Manage incidents." },
      { control_id: "RS.AN", title: "Incident Analysis", category: "incident_response", description: "Analyze incidents." },
      { control_id: "RS.CO", title: "Incident Response Communication", category: "incident_response", description: "Communicate during incidents." },
      { control_id: "RS.MI", title: "Incident Mitigation", category: "incident_response", description: "Mitigate incidents." },
      { control_id: "RC.RP", title: "Recovery Plan", category: "business_continuity", description: "Plan recovery." },
      { control_id: "RC.CO", title: "Recovery Communication", category: "business_continuity", description: "Communicate during recovery." }
    ]
  },
  {
    key: "cis_v8",
    name: "CIS Controls v8",
    version: "8.0",
    description: "18 prioritized safeguards (IG1/IG2/IG3).",
    controls: [
      { control_id: "CIS-01", title: "Inventory and Control of Enterprise Assets", category: "asset_management", description: "Inventory hardware assets." },
      { control_id: "CIS-02", title: "Inventory and Control of Software Assets", category: "asset_management", description: "Inventory software assets." },
      { control_id: "CIS-03", title: "Data Protection", category: "data_protection", description: "Protect data." },
      { control_id: "CIS-04", title: "Secure Configuration of Enterprise Assets and Software", category: "security_operations", description: "Secure configurations." },
      { control_id: "CIS-05", title: "Account Management", category: "access_control", description: "Manage accounts." },
      { control_id: "CIS-06", title: "Access Control Management", category: "access_control", description: "Manage access controls." },
      { control_id: "CIS-07", title: "Continuous Vulnerability Management", category: "security_operations", description: "Manage vulnerabilities." },
      { control_id: "CIS-08", title: "Audit Log Management", category: "security_operations", description: "Manage audit logs." },
      { control_id: "CIS-09", title: "Email and Web Browser Protections", category: "network_security", description: "Protect email and browsers." },
      { control_id: "CIS-10", title: "Malware Defenses", category: "security_operations", description: "Defend against malware." },
      { control_id: "CIS-11", title: "Data Recovery", category: "business_continuity", description: "Recover data." },
      { control_id: "CIS-12", title: "Network Infrastructure Management", category: "network_security", description: "Manage network infrastructure." },
      { control_id: "CIS-13", title: "Network Monitoring and Defense", category: "network_security", description: "Monitor and defend networks." },
      { control_id: "CIS-14", title: "Security Awareness and Skills Training", category: "human_resources", description: "Security training." },
      { control_id: "CIS-15", title: "Service Provider Management", category: "compliance", description: "Manage service providers." },
      { control_id: "CIS-16", title: "Application Software Security", category: "security_operations", description: "Secure application software." },
      { control_id: "CIS-17", title: "Incident Response Management", category: "incident_response", description: "Manage incident response." },
      { control_id: "CIS-18", title: "Penetration Testing", category: "security_operations", description: "Conduct penetration testing." }
    ]
  },

  // ── Curated Starter Subsets (fast initial pass — full library can be imported later; duplicates are skipped) ─
  {
    key: "iso27001_starter",
    name: "ISO 27001:2022 Starter (Essential 30)",
    version: "2022",
    tag: "Starter",
    description: "The 30 most-cited Annex A controls — a fast first pass for new tenants. Import the full library later to top up; duplicates are skipped automatically.",
    controls: [
      { control_id: "A.5.1", title: "Policies for information security", category: "compliance", description: "Author and approve information security policies." },
      { control_id: "A.5.2", title: "Information security roles and responsibilities", category: "access_control", description: "Allocate roles and responsibilities for security." },
      { control_id: "A.5.3", title: "Segregation of duties", category: "access_control", description: "Separate conflicting duties to reduce risk." },
      { control_id: "A.5.9", title: "Inventory of information and other associated assets", category: "asset_management", description: "Maintain an inventory of assets." },
      { control_id: "A.5.12", title: "Classification of information", category: "data_protection", description: "Classify information by sensitivity." },
      { control_id: "A.5.15", title: "Access control", category: "access_control", description: "Define access control rules." },
      { control_id: "A.5.16", title: "Identity management", category: "access_control", description: "Manage identities lifecycle." },
      { control_id: "A.5.17", title: "Authentication information", category: "access_control", description: "Manage authentication information." },
      { control_id: "A.5.18", title: "Access rights", category: "access_control", description: "Grant and revoke access rights." },
      { control_id: "A.5.23", title: "Information security for use of cloud services", category: "compliance", description: "Define security for cloud services." },
      { control_id: "A.5.24", title: "Information security incident management planning and preparation", category: "incident_response", description: "Plan and prepare for incidents." },
      { control_id: "A.5.25", title: "Assessment and decision on information security events", category: "incident_response", description: "Assess security events." },
      { control_id: "A.5.26", title: "Response to information security incidents", category: "incident_response", description: "Respond to incidents." },
      { control_id: "A.5.31", title: "Legal, statutory, regulatory and contractual requirements", category: "compliance", description: "Identify and meet legal requirements." },
      { control_id: "A.5.34", title: "Privacy and protection of PII", category: "compliance", description: "Protect personal data." },
      { control_id: "A.6.1", title: "Screening", category: "human_resources", description: "Screen personnel before employment." },
      { control_id: "A.6.3", title: "Information security awareness, education and training", category: "human_resources", description: "Provide security awareness training." },
      { control_id: "A.7.1", title: "Physical security perimeters", category: "physical_security", description: "Define physical security perimeters." },
      { control_id: "A.7.2", title: "Physical entry", category: "physical_security", description: "Control physical entry." },
      { control_id: "A.8.1", title: "User endpoint devices", category: "access_control", description: "Secure user endpoint devices." },
      { control_id: "A.8.2", title: "Privileged access rights", category: "access_control", description: "Manage privileged access rights." },
      { control_id: "A.8.5", title: "Secure authentication", category: "access_control", description: "Implement secure authentication." },
      { control_id: "A.8.7", title: "Protection against malware", category: "security_operations", description: "Protect against malware." },
      { control_id: "A.8.8", title: "Management of technical vulnerabilities", category: "security_operations", description: "Manage technical vulnerabilities." },
      { control_id: "A.8.13", title: "Information backup", category: "data_protection", description: "Back up information." },
      { control_id: "A.8.15", title: "Logging", category: "security_operations", description: "Log events." },
      { control_id: "A.8.16", title: "Monitoring activities", category: "security_operations", description: "Monitor systems." },
      { control_id: "A.8.20", title: "Networks security", category: "network_security", description: "Secure networks." },
      { control_id: "A.8.24", title: "Use of cryptography", category: "data_protection", description: "Use cryptography appropriately." },
      { control_id: "A.8.32", title: "Change management", category: "change_management", description: "Manage changes." }
    ]
  },
  {
    key: "soc2_starter",
    name: "SOC 2 Starter (Essential 25)",
    version: "2017",
    tag: "Starter",
    description: "The 25 highest-impact SOC 2 Trust Service Criteria controls covering governance, access, monitoring, incident response, and change management. Import the full library later to top up.",
    controls: [
      { control_id: "CC1.1", title: "Demonstrate commitment to integrity and ethical values", category: "compliance", description: "Tone at the top." },
      { control_id: "CC1.2", title: "Exercise oversight responsibility", category: "compliance", description: "Board oversight of the system." },
      { control_id: "CC1.3", title: "Establish structure, authority and responsibility", category: "compliance", description: "Organizational structure." },
      { control_id: "CC1.5", title: "Enforce accountability", category: "compliance", description: "Accountability for controls." },
      { control_id: "CC2.1", title: "Obtain and use relevant, quality information", category: "compliance", description: "Information for internal control." },
      { control_id: "CC2.2", title: "Communicate internally", category: "compliance", description: "Internal communication of objectives." },
      { control_id: "CC2.3", title: "Communicate externally", category: "compliance", description: "External communication of objectives." },
      { control_id: "CC3.1", title: "Identify and assess risk", category: "risk_management", description: "Identify risks to objectives." },
      { control_id: "CC3.3", title: "Select and develop risk responses", category: "risk_management", description: "Risk responses." },
      { control_id: "CC3.4", title: "Assess changes in risk", category: "risk_management", description: "Assess changes impacting risk." },
      { control_id: "CC4.1", title: "Conduct ongoing and/or separate evaluations", category: "security_operations", description: "Monitoring of controls." },
      { control_id: "CC4.2", title: "Evaluate and communicate deficiencies", category: "security_operations", description: "Communicate deficiencies." },
      { control_id: "CC5.1", title: "Select and develop control activities", category: "security_operations", description: "Control activities." },
      { control_id: "CC5.2", title: "Select and develop general controls over technology", category: "security_operations", description: "IT general controls." },
      { control_id: "CC5.3", title: "Deploy controls through policies and procedures", category: "compliance", description: "Deploy control activities." },
      { control_id: "CC6.1", title: "Logical and physical access controls", category: "access_control", description: "Implement logical access security." },
      { control_id: "CC6.2", title: "Prior to access, identify and authenticate users", category: "access_control", description: "User identification and authentication." },
      { control_id: "CC6.3", title: "Authorize, modify and remove access", category: "access_control", description: "Access provisioning lifecycle." },
      { control_id: "CC6.6", title: "External vendor and business partner access", category: "access_control", description: "Manage external access." },
      { control_id: "CC6.7", title: "Confidentiality and transmission of data", category: "data_protection", description: "Protect data in transit." },
      { control_id: "CC7.1", title: "Detect anomalies and security events", category: "security_operations", description: "Detect security events." },
      { control_id: "CC7.2", title: "Monitor system performance", category: "security_operations", description: "Monitor performance." },
      { control_id: "CC7.3", title: "Evaluate security events to determine incidents", category: "incident_response", description: "Evaluate events for incidents." },
      { control_id: "CC7.4", title: "Respond to and recover from incidents", category: "incident_response", description: "Incident response." },
      { control_id: "CC8.1", title: "Authorize, document, test and approve changes", category: "change_management", description: "Change management." }
    ]
  },

  // ── SADC & Regional Frameworks ───────────────────────────────────────────
  {
    key: "popia_starter",
    name: "POPIA (South Africa)",
    version: "2013 (Effective 2021)",
    tag: "SADC",
    description: "Essential controls under South Africa's Protection of Personal Information Act — the 8 conditions for lawful processing, data subject rights, and breach notification.",
    controls: [
      { control_id: "POPIA-01", title: "Lawful basis for processing", category: "compliance", description: "Identify and document a lawful basis before processing personal information." },
      { control_id: "POPIA-02", title: "Data subject consent management", category: "compliance", description: "Obtain, record, and honour withdrawal of consent for processing." },
      { control_id: "POPIA-03", title: "Processing limitation (data minimisation)", category: "data_protection", description: "Collect only the minimum personal information necessary for the purpose." },
      { control_id: "POPIA-04", title: "Purpose specification", category: "compliance", description: "Process personal information only for the explicitly defined purpose." },
      { control_id: "POPIA-05", title: "Data retention and destruction", category: "data_protection", description: "Retain personal information only as long as necessary, then securely destroy or anonymise." },
      { control_id: "POPIA-06", title: "Data quality assurance", category: "data_protection", description: "Ensure personal information is accurate, complete, and kept up to date." },
      { control_id: "POPIA-07", title: "Openness and transparency (privacy notices)", category: "compliance", description: "Provide clear privacy notices describing processing activities and data subject rights." },
      { control_id: "POPIA-08", title: "Security safeguards — technical measures", category: "security_operations", description: "Implement technical safeguards (encryption, access control, logging) to protect personal information." },
      { control_id: "POPIA-09", title: "Security safeguards — organisational measures", category: "compliance", description: "Implement policies, procedures, and staff training to safeguard personal information." },
      { control_id: "POPIA-10", title: "Data subject right — access", category: "compliance", description: "Provide data subjects with access to their personal information on request." },
      { control_id: "POPIA-11", title: "Data subject right — correction and deletion", category: "compliance", description: "Allow data subjects to correct or request deletion of inaccurate personal information." },
      { control_id: "POPIA-12", title: "Data subject right — objection", category: "compliance", description: "Honour data subject objections to processing for direct marketing or other purposes." },
      { control_id: "POPIA-13", title: "Breach notification to Information Regulator", category: "incident_response", description: "Notify the Information Regulator of compromised personal information as soon as reasonably possible." },
      { control_id: "POPIA-14", title: "Breach notification to data subjects", category: "incident_response", description: "Notify affected data subjects of breaches where there is a risk of harm." },
      { control_id: "POPIA-15", title: "Cross-border transfer safeguards", category: "compliance", description: "Ensure adequate safeguards before transferring personal information outside South Africa." },
      { control_id: "POPIA-16", title: "Information Officer registration", category: "compliance", description: "Register the Information Officer with the Information Regulator." },
      { control_id: "POPIA-17", title: "PAIA manual maintenance", category: "compliance", description: "Maintain and publish a PAIA manual describing access to information procedures." },
      { control_id: "POPIA-18", title: "Direct marketing opt-out", category: "compliance", description: "Provide and honour opt-out mechanisms for electronic direct marketing." }
    ]
  },
  {
    key: "fsra_cyber_starter",
    name: "FSRA Cyber Rules (Botswana)",
    version: "2021",
    tag: "SADC",
    description: "Essential cybersecurity controls for FSRA-regulated financial entities in Botswana — governance, access, monitoring, incident response, vendor risk, and penetration testing.",
    controls: [
      { control_id: "FSRA-01", title: "Board and senior management cyber oversight", category: "compliance", description: "Establish board-level accountability for cybersecurity risk." },
      { control_id: "FSRA-02", title: "Cyber risk governance framework", category: "risk_management", description: "Document and maintain a cyber risk governance framework approved by the board." },
      { control_id: "FSRA-03", title: "Cybersecurity policy and standards", category: "compliance", description: "Maintain approved cybersecurity policies and technical standards." },
      { control_id: "FSRA-04", title: "Risk assessment and threat modelling", category: "risk_management", description: "Conduct regular cyber risk assessments and threat modelling exercises." },
      { control_id: "FSRA-05", title: "Access control and identity management", category: "access_control", description: "Enforce least-privilege access and robust identity management across all systems." },
      { control_id: "FSRA-06", title: "Privileged access management", category: "access_control", description: "Monitor and restrict privileged accounts using vaulting and session controls." },
      { control_id: "FSRA-07", title: "Network security and segmentation", category: "network_security", description: "Segment networks and protect boundaries to limit lateral movement." },
      { control_id: "FSRA-08", title: "Endpoint and malware protection", category: "security_operations", description: "Deploy endpoint detection and anti-malware across all managed devices." },
      { control_id: "FSRA-09", title: "Vulnerability management and patching", category: "security_operations", description: "Scan, prioritise, and remediate vulnerabilities within defined SLAs." },
      { control_id: "FSRA-10", title: "SIEM and security monitoring", category: "security_operations", description: "Implement SIEM with 24/7 monitoring and alerting for security events." },
      { control_id: "FSRA-11", title: "Incident response plan and testing", category: "incident_response", description: "Maintain and annually test a documented incident response plan." },
      { control_id: "FSRA-12", title: "Breach notification to FSRA", category: "incident_response", description: "Report material cyber incidents to FSRA within the required timeframe." },
      { control_id: "FSRA-13", title: "Third-party and vendor risk management", category: "risk_management", description: "Assess and monitor cybersecurity risk of third-party providers and vendors." },
      { control_id: "FSRA-14", title: "Business continuity and disaster recovery", category: "business_continuity", description: "Maintain tested BCDR plans ensuring critical services resilience." },
      { control_id: "FSRA-15", title: "Penetration testing (annual)", category: "security_operations", description: "Conduct annual independent penetration testing and remediate findings." },
      { control_id: "FSRA-16", title: "Staff cybersecurity awareness training", category: "human_resources", description: "Provide ongoing cybersecurity awareness training to all staff." }
    ]
  },
  {
    key: "kenya_dpa_starter",
    name: "Kenya DPA (Data Protection Act)",
    version: "2019",
    tag: "SADC",
    description: "Essential controls under Kenya's Data Protection Act — controller registration, consent, data subject rights, breach notification, and cross-border transfers.",
    controls: [
      { control_id: "KE-DPA-01", title: "Data controller and processor registration", category: "compliance", description: "Register as a data controller/processor with the Office of the Data Protection Commissioner." },
      { control_id: "KE-DPA-02", title: "Lawful basis for processing", category: "compliance", description: "Identify and document a lawful basis before processing personal data." },
      { control_id: "KE-DPA-03", title: "Consent management", category: "compliance", description: "Obtain, record, and honour withdrawal of consent for processing personal data." },
      { control_id: "KE-DPA-04", title: "Data protection by design and by default", category: "compliance", description: "Embed data protection into systems and processes from the design stage." },
      { control_id: "KE-DPA-05", title: "Privacy impact assessments (DPIA)", category: "risk_management", description: "Conduct DPIAs for high-risk processing activities." },
      { control_id: "KE-DPA-06", title: "Data subject right — access", category: "compliance", description: "Provide data subjects with access to their personal data on request." },
      { control_id: "KE-DPA-07", title: "Data subject right — rectification and erasure", category: "compliance", description: "Allow data subjects to rectify or request erasure of their personal data." },
      { control_id: "KE-DPA-08", title: "Data subject right — portability", category: "compliance", description: "Provide personal data in a structured, machine-readable format on request." },
      { control_id: "KE-DPA-09", title: "Security measures (technical and organisational)", category: "security_operations", description: "Implement appropriate technical and organisational security measures to protect personal data." },
      { control_id: "KE-DPA-10", title: "Breach notification (72h to ODPC)", category: "incident_response", description: "Notify the ODPC of personal data breaches within 72 hours of becoming aware." },
      { control_id: "KE-DPA-11", title: "Cross-border transfer safeguards", category: "compliance", description: "Ensure adequate safeguards before transferring personal data outside Kenya." },
      { control_id: "KE-DPA-12", title: "Data retention and deletion schedule", category: "data_protection", description: "Maintain a retention schedule and securely delete data when retention periods expire." },
      { control_id: "KE-DPA-13", title: "Data Protection Officer appointment", category: "compliance", description: "Appoint a DPO where required and ensure their independence." },
      { control_id: "KE-DPA-14", title: "Privacy notices and transparency", category: "compliance", description: "Provide clear privacy notices describing processing activities and data subject rights." },
      { control_id: "KE-DPA-15", title: "Direct marketing restrictions", category: "compliance", description: "Comply with consent and opt-out requirements for direct marketing." }
    ]
  }
];