// Pre-Built Framework Control Templates — Out-of-the-Box Mappings
// 28 frameworks, each with pre-mapped requirements → controls → automated test keys.
// When a user applies a template, the platform creates requirements, controls, control tests,
// and the mappings between them — so connecting a tool auto-populates and auto-tests controls.

export const FRAMEWORK_TEMPLATES = [
  {
    code: "SOC2",
    name: "SOC 2 (AICPA Trust Services Criteria)",
    version: "2017 TSC",
    jurisdiction: "global",
    authority: "AICPA",
    description: "Service Organization Control 2 — security, availability, processing integrity, confidentiality, and privacy.",
    requirements: [
      { requirement_id: "CC1.1", title: "Control Environment - Integrity and Ethics", category: "compliance", is_mandatory: true },
      { requirement_id: "CC2.1", title: "Communication and Information - Internal Communication", category: "compliance", is_mandatory: true },
      { requirement_id: "CC3.1", title: "Risk Assessment - Identification and Analysis", category: "risk_management", is_mandatory: true },
      { requirement_id: "CC4.1", title: "Monitoring Activities - Ongoing Evaluations", category: "security_operations", is_mandatory: true },
      { requirement_id: "CC5.1", title: "Control Activities - Design and Implementation", category: "access_control", is_mandatory: true },
      { requirement_id: "CC6.1", title: "Logical and Physical Access - User Authentication", category: "access_control", is_mandatory: true },
      { requirement_id: "CC6.2", title: "Logical and Physical Access - Access Removal", category: "access_control", is_mandatory: true },
      { requirement_id: "CC6.3", title: "Logical and Physical Access - Network Access", category: "network_security", is_mandatory: true },
      { requirement_id: "CC7.1", title: "System Operations - Vulnerability Detection", category: "security_operations", is_mandatory: true },
      { requirement_id: "CC7.2", title: "System Operations - Incident Detection", category: "incident_response", is_mandatory: true },
      { requirement_id: "CC8.1", title: "Change Management - Software Lifecycle", category: "change_management", is_mandatory: true },
      { requirement_id: "CC9.1", title: "Risk Mitigation - Business Continuity", category: "business_continuity", is_mandatory: true },
      { requirement_id: "A1.1", title: "Availability - Environmental Protections", category: "business_continuity", is_mandatory: false },
      { requirement_id: "C1.1", title: "Confidentiality - Data Encryption", category: "data_protection", is_mandatory: true },
      { requirement_id: "P1.1", title: "Privacy - Data Collection and Use", category: "compliance", is_mandatory: false },
    ],
    controls: [
      { control_id: "SOC2-001", title: "MFA Enforced on All Systems", category: "access_control", description: "Multi-factor authentication enforced on all user accounts and admin consoles", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "SOC2-002", title: "Access Reviews - Quarterly", category: "access_control", description: "Quarterly access reviews for all systems and applications", automation_status: "automated", test_key: "check_access_reviews" },
      { control_id: "SOC2-003", title: "Offboarding Within 24 Hours", category: "access_control", description: "Deprovision access within 24 hours of termination", automation_status: "automated", test_key: "check_offboarding_timeliness" },
      { control_id: "SOC2-004", title: "Vulnerability Scanning - Weekly", category: "security_operations", description: "Weekly automated vulnerability scanning on all infrastructure", automation_status: "automated", test_key: "check_vuln_scans" },
      { control_id: "SOC2-005", title: "Incident Response Plan", category: "incident_response", description: "Documented and tested incident response plan", automation_status: "partially_automated", test_key: "check_ir_plan_exists" },
      { control_id: "SOC2-006", title: "Encryption at Rest (AES-256)", category: "data_protection", description: "AES-256 encryption for all data at rest", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "SOC2-007", title: "Encryption in Transit (TLS 1.2+)", category: "data_protection", description: "TLS 1.2+ for all data in transit", automation_status: "automated", test_key: "check_tls_config" },
      { control_id: "SOC2-008", title: "Change Management - Code Review", category: "change_management", description: "All code changes require peer review before deployment", automation_status: "automated", test_key: "check_code_reviews" },
      { control_id: "SOC2-009", title: "Backup and Recovery", category: "business_continuity", description: "Automated backups with tested recovery procedures", automation_status: "automated", test_key: "check_backups" },
      { control_id: "SOC2-010", title: "Risk Assessment - Annual", category: "risk_management", description: "Annual risk assessment with documented findings", automation_status: "manual", test_key: null },
    ],
    mappings: {
      "CC1.1": ["SOC2-010"], "CC2.1": ["SOC2-005"], "CC3.1": ["SOC2-010"], "CC4.1": ["SOC2-004", "SOC2-002"],
      "CC5.1": ["SOC2-008"], "CC6.1": ["SOC2-001"], "CC6.2": ["SOC2-003"], "CC6.3": ["SOC2-007"],
      "CC7.1": ["SOC2-004"], "CC7.2": ["SOC2-005"], "CC8.1": ["SOC2-008"], "CC9.1": ["SOC2-009"],
      "A1.1": ["SOC2-009"], "C1.1": ["SOC2-006", "SOC2-007"], "P1.1": ["SOC2-006"],
    },
  },
  {
    code: "ISO27001",
    name: "ISO/IEC 27001",
    version: "2022",
    jurisdiction: "global",
    authority: "ISO/IEC",
    description: "Information security management system (ISMS) requirements.",
    requirements: [
      { requirement_id: "A.5.1", title: "Policies for Information Security", category: "compliance", is_mandatory: true },
      { requirement_id: "A.5.2", title: "Information Security Roles and Responsibilities", category: "access_control", is_mandatory: true },
      { requirement_id: "A.5.3", title: "Segregation of Duties", category: "access_control", is_mandatory: true },
      { requirement_id: "A.5.7", title: "Threat Intelligence", category: "security_operations", is_mandatory: true },
      { requirement_id: "A.5.10", title: "Acceptable Use of Information", category: "compliance", is_mandatory: true },
      { requirement_id: "A.6.1", title: "Screening of Personnel", category: "human_resources", is_mandatory: true },
      { requirement_id: "A.6.3", title: "Information Security Awareness and Training", category: "human_resources", is_mandatory: true },
      { requirement_id: "A.7.2", title: "Physical Entry", category: "physical_security", is_mandatory: true },
      { requirement_id: "A.8.1", title: "User Endpoint Devices", category: "asset_management", is_mandatory: true },
      { requirement_id: "A.8.2", title: "Privileged Access Rights", category: "access_control", is_mandatory: true },
      { requirement_id: "A.8.3", title: "Information Access Restriction", category: "access_control", is_mandatory: true },
      { requirement_id: "A.8.5", title: "Secure Authentication", category: "access_control", is_mandatory: true },
      { requirement_id: "A.8.7", title: "Protection Against Malware", category: "security_operations", is_mandatory: true },
      { requirement_id: "A.8.9", title: "Configuration Management", category: "change_management", is_mandatory: true },
      { requirement_id: "A.8.10", title: "Information Deletion", category: "data_protection", is_mandatory: true },
      { requirement_id: "A.8.11", title: "Data Masking", category: "data_protection", is_mandatory: true },
      { requirement_id: "A.8.12", title: "Data Leakage Prevention", category: "data_protection", is_mandatory: true },
      { requirement_id: "A.8.24", title: "Use of Cryptography", category: "data_protection", is_mandatory: true },
      { requirement_id: "A.8.28", title: "Secure Coding", category: "change_management", is_mandatory: true },
      { requirement_id: "A.8.29", title: "Security Testing in Development", category: "change_management", is_mandatory: true },
      { requirement_id: "A.8.34", title: "Protection of Systems During Attacks", category: "security_operations", is_mandatory: true },
      { requirement_id: "A.9.1", title: "Management of Technical Vulnerabilities", category: "security_operations", is_mandatory: true },
      { requirement_id: "A.5.24", title: "Information Security Incident Management Planning", category: "incident_response", is_mandatory: true },
      { requirement_id: "A.5.30", title: "ICT Readiness for Business Continuity", category: "business_continuity", is_mandatory: true },
    ],
    controls: [
      { control_id: "ISO-001", title: "Information Security Policy Reviewed Annually", category: "compliance", description: "ISMS policy documented and reviewed annually", automation_status: "manual", test_key: null },
      { control_id: "ISO-002", title: "MFA on All Access", category: "access_control", description: "Multi-factor authentication enforced globally", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "ISO-003", title: "Privileged Access Management", category: "access_control", description: "PAM solution with just-in-time access for privileged accounts", automation_status: "automated", test_key: "check_pam_config" },
      { control_id: "ISO-004", title: "Security Awareness Training - Annual", category: "human_resources", description: "Annual security awareness training for all employees", automation_status: "automated", test_key: "check_training_completion" },
      { control_id: "ISO-005", title: "Endpoint Protection (EDR)", category: "security_operations", description: "EDR deployed on all endpoints with centralized monitoring", automation_status: "automated", test_key: "check_edr_coverage" },
      { control_id: "ISO-006", title: "Vulnerability Management Program", category: "security_operations", description: "Monthly vulnerability scanning with remediation SLAs", automation_status: "automated", test_key: "check_vuln_scans" },
      { control_id: "ISO-007", title: "Encryption at Rest and in Transit", category: "data_protection", description: "AES-256 at rest, TLS 1.2+ in transit", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "ISO-008", title: "DLP Solution Deployed", category: "data_protection", description: "Data loss prevention monitoring on email and endpoints", automation_status: "automated", test_key: "check_dlp_config" },
      { control_id: "ISO-009", title: "Secure SDLC - SAST/DAST", category: "change_management", description: "SAST and DAST scanning in CI/CD pipeline", automation_status: "automated", test_key: "check_devsecops_pipeline" },
      { control_id: "ISO-010", title: "Incident Response Plan Tested", category: "incident_response", description: "IR plan tested annually via tabletop exercise", automation_status: "manual", test_key: null },
      { control_id: "ISO-011", title: "Backup and DR Tested", category: "business_continuity", description: "Backups tested quarterly with DR exercise", automation_status: "automated", test_key: "check_backups" },
      { control_id: "ISO-012", title: "Access Review - Quarterly", category: "access_control", description: "Quarterly user access reviews", automation_status: "automated", test_key: "check_access_reviews" },
    ],
    mappings: {
      "A.5.1": ["ISO-001"], "A.5.2": ["ISO-001"], "A.5.3": ["ISO-003"], "A.5.7": ["ISO-005"],
      "A.5.10": ["ISO-001"], "A.6.1": ["ISO-004"], "A.6.3": ["ISO-004"], "A.7.2": ["ISO-003"],
      "A.8.1": ["ISO-005"], "A.8.2": ["ISO-003"], "A.8.3": ["ISO-012"], "A.8.5": ["ISO-002"],
      "A.8.7": ["ISO-005"], "A.8.9": ["ISO-009"], "A.8.10": ["ISO-008"], "A.8.11": ["ISO-008"],
      "A.8.12": ["ISO-008"], "A.8.24": ["ISO-007"], "A.8.28": ["ISO-009"], "A.8.29": ["ISO-009"],
      "A.8.34": ["ISO-005"], "A.9.1": ["ISO-006"], "A.5.24": ["ISO-010"], "A.5.30": ["ISO-011"],
    },
  },
  {
    code: "NIST_CSF",
    name: "NIST Cybersecurity Framework",
    version: "2.0",
    jurisdiction: "us",
    authority: "NIST",
    description: "Identify, Protect, Detect, Respond, Recover — core cybersecurity functions.",
    requirements: [
      { requirement_id: "ID.AM-1", title: "Inventory of Devices", category: "asset_management", is_mandatory: true },
      { requirement_id: "ID.RA-1", title: "Asset Vulnerabilities Identified", category: "risk_management", is_mandatory: true },
      { requirement_id: "PR.AC-1", title: "Identity and Credential Management", category: "access_control", is_mandatory: true },
      { requirement_id: "PR.AC-4", title: "Access Permissions Managed", category: "access_control", is_mandatory: true },
      { requirement_id: "PR.DS-1", title: "Data-at-Rest Security", category: "data_protection", is_mandatory: true },
      { requirement_id: "PR.DS-2", title: "Data-in-Transit Security", category: "data_protection", is_mandatory: true },
      { requirement_id: "PR.IP-1", title: "Configuration Baselines", category: "change_management", is_mandatory: true },
      { requirement_id: "PR.IP-12", title: "Vulnerability Management Plan", category: "security_operations", is_mandatory: true },
      { requirement_id: "DE.CM-1", title: "Network Monitored", category: "security_operations", is_mandatory: true },
      { requirement_id: "DE.CM-8", title: "Vulnerability Scans Performed", category: "security_operations", is_mandatory: true },
      { requirement_id: "RS.RP-1", title: "Response Plan Defined", category: "incident_response", is_mandatory: true },
      { requirement_id: "RC.RP-1", title: "Recovery Plan Defined", category: "business_continuity", is_mandatory: true },
    ],
    controls: [
      { control_id: "NIST-001", title: "Asset Inventory - Automated", category: "asset_management", description: "Automated asset discovery and inventory", automation_status: "automated", test_key: "check_asset_inventory" },
      { control_id: "NIST-002", title: "MFA Enforced", category: "access_control", description: "MFA on all accounts", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "NIST-003", title: "Quarterly Access Reviews", category: "access_control", description: "Periodic access recertification", automation_status: "automated", test_key: "check_access_reviews" },
      { control_id: "NIST-004", title: "Disk Encryption", category: "data_protection", description: "Full disk encryption on all endpoints", automation_status: "automated", test_key: "check_disk_encryption" },
      { control_id: "NIST-005", title: "TLS 1.2+ Enforced", category: "data_protection", description: "TLS 1.2+ for all connections", automation_status: "automated", test_key: "check_tls_config" },
      { control_id: "NIST-006", title: "CIS Benchmarks Applied", category: "change_management", description: "CIS hardening baselines on all systems", automation_status: "automated", test_key: "check_cis_baselines" },
      { control_id: "NIST-007", title: "Vulnerability Scanning - Monthly", category: "security_operations", description: "Monthly vuln scans with SLA tracking", automation_status: "automated", test_key: "check_vuln_scans" },
      { control_id: "NIST-008", title: "SIEM/SOC Monitoring", category: "security_operations", description: "24/7 SIEM monitoring with alerting", automation_status: "automated", test_key: "check_siem_config" },
      { control_id: "NIST-009", title: "Incident Response Plan", category: "incident_response", description: "Documented IR plan with annual testing", automation_status: "manual", test_key: null },
      { control_id: "NIST-010", title: "Backup and Recovery", category: "business_continuity", description: "Tested backup and DR procedures", automation_status: "automated", test_key: "check_backups" },
    ],
    mappings: {
      "ID.AM-1": ["NIST-001"], "ID.RA-1": ["NIST-007"], "PR.AC-1": ["NIST-002"], "PR.AC-4": ["NIST-003"],
      "PR.DS-1": ["NIST-004"], "PR.DS-2": ["NIST-005"], "PR.IP-1": ["NIST-006"], "PR.IP-12": ["NIST-007"],
      "DE.CM-1": ["NIST-008"], "DE.CM-8": ["NIST-007"], "RS.RP-1": ["NIST-009"], "RC.RP-1": ["NIST-010"],
    },
  },
  {
    code: "GDPR",
    name: "GDPR (General Data Protection Regulation)",
    version: "2018",
    jurisdiction: "eu",
    authority: "European Parliament",
    description: "EU General Data Protection Regulation — data protection and privacy.",
    requirements: [
      { requirement_id: "Art.5", title: "Principles Relating to Processing of Personal Data", category: "data_protection", is_mandatory: true },
      { requirement_id: "Art.6", title: "Lawfulness of Processing", category: "compliance", is_mandatory: true },
      { requirement_id: "Art.7", title: "Conditions for Consent", category: "compliance", is_mandatory: true },
      { requirement_id: "Art.9", title: "Processing of Special Categories of Data", category: "data_protection", is_mandatory: true },
      { requirement_id: "Art.12", title: "Transparent Information and Communication", category: "compliance", is_mandatory: true },
      { requirement_id: "Art.15", title: "Right of Access by the Data Subject", category: "compliance", is_mandatory: true },
      { requirement_id: "Art.17", title: "Right to Erasure (Right to be Forgotten)", category: "compliance", is_mandatory: true },
      { requirement_id: "Art.25", title: "Data Protection by Design and by Default", category: "data_protection", is_mandatory: true },
      { requirement_id: "Art.28", title: "Processor Obligations", category: "compliance", is_mandatory: true },
      { requirement_id: "Art.32", title: "Security of Processing", category: "data_protection", is_mandatory: true },
      { requirement_id: "Art.33", title: "Notification of Personal Data Breach to Authority", category: "incident_response", is_mandatory: true },
      { requirement_id: "Art.34", title: "Communication of Personal Data Breach to Data Subject", category: "incident_response", is_mandatory: true },
      { requirement_id: "Art.35", title: "Data Protection Impact Assessment", category: "risk_management", is_mandatory: true },
      { requirement_id: "Art.37", title: "Designation of the DPO", category: "compliance", is_mandatory: true },
      { requirement_id: "Art.44", title: "Transfers of Personal Data to Third Countries", category: "compliance", is_mandatory: true },
    ],
    controls: [
      { control_id: "GDPR-001", title: "Data Processing Register (ROPA)", category: "compliance", description: "Records of processing activities maintained", automation_status: "manual", test_key: null },
      { control_id: "GDPR-002", title: "Consent Management System", category: "compliance", description: "Consent records tracked and revocable", automation_status: "automated", test_key: "check_consent_records" },
      { control_id: "GDPR-003", title: "Data Subject Request Workflow", category: "compliance", description: "DSAR workflow with 30-day SLA", automation_status: "automated", test_key: "check_dsar_workflow" },
      { control_id: "GDPR-004", title: "Data Encryption (At Rest and in Transit)", category: "data_protection", description: "AES-256 at rest, TLS 1.2+ in transit", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "GDPR-005", title: "Pseudonymization/Anonymization", category: "data_protection", description: "PII pseudonymization where feasible", automation_status: "automated", test_key: "check_data_masking" },
      { control_id: "GDPR-006", title: "Breach Notification Process (72h)", category: "incident_response", description: "72-hour breach notification to authority", automation_status: "automated", test_key: "check_breach_notification_sla" },
      { control_id: "GDPR-007", title: "DPIA Process for High-Risk Processing", category: "risk_management", description: "DPIA conducted for high-risk processing", automation_status: "manual", test_key: null },
      { control_id: "GDPR-008", title: "DPO Appointed", category: "compliance", description: "Data Protection Officer designated", automation_status: "manual", test_key: null },
      { control_id: "GDPR-009", title: "Data Transfer Impact Assessment", category: "compliance", description: "TIA for cross-border transfers", automation_status: "manual", test_key: null },
      { control_id: "GDPR-010", title: "Vendor Data Processing Agreements", category: "compliance", description: "DPA with all processors (Art. 28)", automation_status: "manual", test_key: null },
    ],
    mappings: {
      "Art.5": ["GDPR-001", "GDPR-004"], "Art.6": ["GDPR-001"], "Art.7": ["GDPR-002"], "Art.9": ["GDPR-005"],
      "Art.12": ["GDPR-003"], "Art.15": ["GDPR-003"], "Art.17": ["GDPR-003"], "Art.25": ["GDPR-004", "GDPR-005"],
      "Art.28": ["GDPR-010"], "Art.32": ["GDPR-004"], "Art.33": ["GDPR-006"], "Art.34": ["GDPR-006"],
      "Art.35": ["GDPR-007"], "Art.37": ["GDPR-008"], "Art.44": ["GDPR-009"],
    },
  },
  {
    code: "POPIA",
    name: "POPIA (Protection of Personal Information Act)",
    version: "2021",
    jurisdiction: "za",
    authority: "Information Regulator (South Africa)",
    description: "South African data protection law — processing of personal information.",
    requirements: [
      { requirement_id: "S.4", title: "Lawful Processing of Personal Information", category: "compliance", is_mandatory: true },
      { requirement_id: "S.5", title: "Information Quality", category: "data_protection", is_mandatory: true },
      { requirement_id: "S.6", title: "Openness", category: "compliance", is_mandatory: true },
      { requirement_id: "S.7", title: "Security Safeguards", category: "data_protection", is_mandatory: true },
      { requirement_id: "S.8", title: "Data Subject Participation", category: "compliance", is_mandatory: true },
      { requirement_id: "S.11", title: "Consent, Justification and Objection", category: "compliance", is_mandatory: true },
      { requirement_id: "S.18", title: "Direct Marketing", category: "compliance", is_mandatory: true },
      { requirement_id: "S.19", title: "Security Measures", category: "data_protection", is_mandatory: true },
      { requirement_id: "S.20", title: "Operational Requirements", category: "data_protection", is_mandatory: true },
      { requirement_id: "S.21", title: "Notification of Compromise", category: "incident_response", is_mandatory: true },
      { requirement_id: "S.22", title: "Cross-Border Transfer", category: "compliance", is_mandatory: true },
      { requirement_id: "S.57", title: "Appointment of Information Officer", category: "compliance", is_mandatory: true },
    ],
    controls: [
      { control_id: "POPIA-001", title: "PAIA/POPIA Manual", category: "compliance", description: "Section 51 PAIA manual with POPIA provisions", automation_status: "manual", test_key: null },
      { control_id: "POPIA-002", title: "Personal Information Register", category: "compliance", description: "Inventory of all PI processing activities", automation_status: "manual", test_key: null },
      { control_id: "POPIA-003", title: "Consent Records", category: "compliance", description: "Consent tracking for direct marketing", automation_status: "automated", test_key: "check_consent_records" },
      { control_id: "POPIA-004", title: "Encryption and Access Controls", category: "data_protection", description: "Technical safeguards for PI", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "POPIA-005", title: "Breach Notification (Regulator + Subject)", category: "incident_response", description: "Notify regulator and data subjects of compromise", automation_status: "automated", test_key: "check_breach_notification_sla" },
      { control_id: "POPIA-006", title: "Cross-Border Transfer Assessment", category: "compliance", description: "Assess adequacy of foreign protection", automation_status: "manual", test_key: null },
      { control_id: "POPIA-007", title: "Information Officer Appointed", category: "compliance", description: "IO registered with Information Regulator", automation_status: "manual", test_key: null },
      { control_id: "POPIA-008", title: "Data Subject Access Requests", category: "compliance", description: "DSAR workflow for PI access", automation_status: "automated", test_key: "check_dsar_workflow" },
    ],
    mappings: {
      "S.4": ["POPIA-002"], "S.5": ["POPIA-002"], "S.6": ["POPIA-001"], "S.7": ["POPIA-004"],
      "S.8": ["POPIA-008"], "S.11": ["POPIA-003"], "S.18": ["POPIA-003"], "S.19": ["POPIA-004"],
      "S.20": ["POPIA-004"], "S.21": ["POPIA-005"], "S.22": ["POPIA-006"], "S.57": ["POPIA-007"],
    },
  },
  {
    code: "HIPAA",
    name: "HIPAA Security Rule",
    version: "2013",
    jurisdiction: "us",
    authority: "HHS OCR",
    description: "Health Insurance Portability and Accountability Act — ePHI protection.",
    requirements: [
      { requirement_id: "164.308(a)(1)", title: "Security Management Process - Risk Analysis", category: "risk_management", is_mandatory: true },
      { requirement_id: "164.308(a)(3)", title: "Workforce Security", category: "access_control", is_mandatory: true },
      { requirement_id: "164.308(a)(4)", title: "Information Access Management", category: "access_control", is_mandatory: true },
      { requirement_id: "164.308(a)(5)", title: "Security Awareness and Training", category: "human_resources", is_mandatory: true },
      { requirement_id: "164.308(a)(6)", title: "Security Incident Procedures", category: "incident_response", is_mandatory: true },
      { requirement_id: "164.308(a)(7)", title: "Contingency Plan", category: "business_continuity", is_mandatory: true },
      { requirement_id: "164.310(a)(1)", title: "Facility Access Controls", category: "physical_security", is_mandatory: true },
      { requirement_id: "164.312(a)(1)", title: "Access Control", category: "access_control", is_mandatory: true },
      { requirement_id: "164.312(b)", title: "Audit Controls", category: "security_operations", is_mandatory: true },
      { requirement_id: "164.312(c)(1)", title: "Integrity Controls", category: "data_protection", is_mandatory: true },
      { requirement_id: "164.312(d)", title: "Person or Entity Authentication", category: "access_control", is_mandatory: true },
      { requirement_id: "164.312(e)(1)", title: "Transmission Security", category: "data_protection", is_mandatory: true },
    ],
    controls: [
      { control_id: "HIPAA-001", title: "Annual Risk Assessment", category: "risk_management", description: "Annual HIPAA risk analysis documented", automation_status: "manual", test_key: null },
      { control_id: "HIPAA-002", title: "Role-Based Access Control", category: "access_control", description: "RBAC for ePHI access", automation_status: "automated", test_key: "check_rbac" },
      { control_id: "HIPAA-003", title: "MFA for ePHI Systems", category: "access_control", description: "MFA on all ePHI-accessible systems", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "HIPAA-004", title: "HIPAA Training - Annual", category: "human_resources", description: "Annual HIPAA security training", automation_status: "automated", test_key: "check_training_completion" },
      { control_id: "HIPAA-005", title: "Audit Log Retention (6 years)", category: "security_operations", description: "Audit logs retained for 6 years", automation_status: "automated", test_key: "check_log_retention" },
      { control_id: "HIPAA-006", title: "ePHI Encryption at Rest", category: "data_protection", description: "AES encryption for all ePHI", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "HIPAA-007", title: "TLS for ePHI Transmission", category: "data_protection", description: "TLS 1.2+ for ePHI in transit", automation_status: "automated", test_key: "check_tls_config" },
      { control_id: "HIPAA-008", title: "Breach Notification Process", category: "incident_response", description: "60-day breach notification process", automation_status: "automated", test_key: "check_breach_notification_sla" },
      { control_id: "HIPAA-009", title: "Disaster Recovery Plan", category: "business_continuity", description: "DR plan with data backup and recovery", automation_status: "automated", test_key: "check_backups" },
    ],
    mappings: {
      "164.308(a)(1)": ["HIPAA-001"], "164.308(a)(3)": ["HIPAA-002"], "164.308(a)(4)": ["HIPAA-002"],
      "164.308(a)(5)": ["HIPAA-004"], "164.308(a)(6)": ["HIPAA-008"], "164.308(a)(7)": ["HIPAA-009"],
      "164.310(a)(1)": ["HIPAA-002"], "164.312(a)(1)": ["HIPAA-003"], "164.312(b)": ["HIPAA-005"],
      "164.312(c)(1)": ["HIPAA-006"], "164.312(d)": ["HIPAA-003"], "164.312(e)(1)": ["HIPAA-007"],
    },
  },
  {
    code: "PCI_DSS",
    name: "PCI DSS (Payment Card Industry Data Security Standard)",
    version: "4.0",
    jurisdiction: "global",
    authority: "PCI SSC",
    description: "Security standard for organizations that handle credit cards.",
    requirements: [
      { requirement_id: "1.1", title: "Firewall and Router Configuration Standards", category: "network_security", is_mandatory: true },
      { requirement_id: "2.1", title: "Vendor Default Passwords Changed", category: "access_control", is_mandatory: true },
      { requirement_id: "3.1", title: "Cardholder Data Retention Limits", category: "data_protection", is_mandatory: true },
      { requirement_id: "3.4", title: "PAN Rendered Unreadable", category: "data_protection", is_mandatory: true },
      { requirement_id: "4.1", title: "Encrypt Transmission of Cardholder Data", category: "data_protection", is_mandatory: true },
      { requirement_id: "5.1", title: "Anti-Virus Software Deployed", category: "security_operations", is_mandatory: true },
      { requirement_id: "6.1", title: "Secure Software Development Process", category: "change_management", is_mandatory: true },
      { requirement_id: "7.1", title: "Restrict Access to Cardholder Data by Need-to-Know", category: "access_control", is_mandatory: true },
      { requirement_id: "8.1", title: "Unique ID for Each Person with Computer Access", category: "access_control", is_mandatory: true },
      { requirement_id: "9.1", title: "Physical Access to Cardholder Data Restricted", category: "physical_security", is_mandatory: true },
      { requirement_id: "10.1", title: "Audit Trails for All System Components", category: "security_operations", is_mandatory: true },
      { requirement_id: "11.1", title: "Quarterly Vulnerability Scans", category: "security_operations", is_mandatory: true },
      { requirement_id: "12.1", title: "Information Security Policy", category: "compliance", is_mandatory: true },
    ],
    controls: [
      { control_id: "PCI-001", title: "Firewall Configurations - Documented", category: "network_security", description: "Firewall rules documented and reviewed semi-annually", automation_status: "automated", test_key: "check_firewall_config" },
      { control_id: "PCI-002", title: "No Default Passwords", category: "access_control", description: "All vendor defaults changed", automation_status: "automated", test_key: "check_default_passwords" },
      { control_id: "PCI-003", title: "PAN Tokenization/Encryption", category: "data_protection", description: "PAN rendered unreadable via tokenization", automation_status: "automated", test_key: "check_pan_tokenization" },
      { control_id: "PCI-004", title: "TLS for Card Data Transmission", category: "data_protection", description: "TLS 1.2+ for cardholder data", automation_status: "automated", test_key: "check_tls_config" },
      { control_id: "PCI-005", title: "EDR/Anti-Malware on All Systems", category: "security_operations", description: "Anti-malware deployed and updated", automation_status: "automated", test_key: "check_edr_coverage" },
      { control_id: "PCI-006", title: "Secure SDLC - SAST/DAST", category: "change_management", description: "Code review and security testing in pipeline", automation_status: "automated", test_key: "check_devsecops_pipeline" },
      { control_id: "PCI-007", title: "RBAC for Cardholder Data", category: "access_control", description: "Need-to-know access enforced", automation_status: "automated", test_key: "check_rbac" },
      { control_id: "PCI-008", title: "MFA for CDE Access", category: "access_control", description: "MFA for all CDE access", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "PCI-009", title: "Audit Logs - Centralized", category: "security_operations", description: "Centralized logging with 1-year retention", automation_status: "automated", test_key: "check_log_retention" },
      { control_id: "PCI-010", title: "Quarterly ASV Scans", category: "security_operations", description: "Quarterly ASV vulnerability scans", automation_status: "automated", test_key: "check_vuln_scans" },
    ],
    mappings: {
      "1.1": ["PCI-001"], "2.1": ["PCI-002"], "3.1": ["PCI-003"], "3.4": ["PCI-003"],
      "4.1": ["PCI-004"], "5.1": ["PCI-005"], "6.1": ["PCI-006"], "7.1": ["PCI-007"],
      "8.1": ["PCI-008"], "9.1": ["PCI-007"], "10.1": ["PCI-009"], "11.1": ["PCI-010"], "12.1": ["PCI-001"],
    },
  },
  {
    code: "ISO27017",
    name: "ISO/IEC 27017 — Cloud Security",
    version: "2015",
    jurisdiction: "global",
    authority: "ISO/IEC",
    description: "Code of practice for information security controls for cloud services.",
    requirements: [
      { requirement_id: "A.5.1", title: "Shared Responsibility Model", category: "compliance", is_mandatory: true },
      { requirement_id: "A.5.2", title: "Cloud Service Provider/Client Relationship", category: "compliance", is_mandatory: true },
      { requirement_id: "A.6.1", title: "Cloud Service Provider Personnel", category: "human_resources", is_mandatory: true },
      { requirement_id: "A.8.1", title: "Cloud Service Asset Inventory", category: "asset_management", is_mandatory: true },
      { requirement_id: "A.9.1", title: "Network Access Control in Cloud", category: "network_security", is_mandatory: true },
      { requirement_id: "A.10.1", title: "Cloud Service Monitoring", category: "security_operations", is_mandatory: true },
    ],
    controls: [
      { control_id: "ISO17-001", title: "Shared Responsibility Matrix", category: "compliance", description: "Documented provider/tenant responsibility split", automation_status: "manual", test_key: null },
      { control_id: "ISO17-002", title: "Cloud Asset Inventory", category: "asset_management", description: "Automated cloud resource inventory", automation_status: "automated", test_key: "check_asset_inventory" },
      { control_id: "ISO17-003", title: "Cloud Network Segmentation", category: "network_security", description: "VPC segmentation and security groups", automation_status: "automated", test_key: "check_network_segmentation" },
      { control_id: "ISO17-004", title: "Cloud Activity Monitoring", category: "security_operations", description: "Cloud trail/audit log monitoring", automation_status: "automated", test_key: "check_cloud_monitoring" },
    ],
    mappings: {
      "A.5.1": ["ISO17-001"], "A.5.2": ["ISO17-001"], "A.6.1": ["ISO17-001"], "A.8.1": ["ISO17-002"],
      "A.9.1": ["ISO17-003"], "A.10.1": ["ISO17-004"],
    },
  },
  {
    code: "ISO27018",
    name: "ISO/IEC 27018 — Cloud Privacy",
    version: "2019",
    jurisdiction: "global",
    authority: "ISO/IEC",
    description: "Code of practice for PII protection in public clouds.",
    requirements: [
      { requirement_id: "A.7.1", title: "PII Controller/Processor Agreement", category: "compliance", is_mandatory: true },
      { requirement_id: "A.7.2", title: "PII Processor Personnel", category: "human_resources", is_mandatory: true },
      { requirement_id: "A.7.3", title: "PII Processing Instructions", category: "compliance", is_mandatory: true },
      { requirement_id: "A.9.1", title: "PII Access Control", category: "access_control", is_mandatory: true },
      { requirement_id: "A.10.1", title: "PII Encryption at Rest", category: "data_protection", is_mandatory: true },
      { requirement_id: "A.11.1", title: "PII Breach Notification", category: "incident_response", is_mandatory: true },
    ],
    controls: [
      { control_id: "ISO18-001", title: "DPA with Cloud Provider", category: "compliance", description: "Data processing agreement in place", automation_status: "manual", test_key: null },
      { control_id: "ISO18-002", title: "PII Access Controls", category: "access_control", description: "RBAC for PII data", automation_status: "automated", test_key: "check_rbac" },
      { control_id: "ISO18-003", title: "PII Encryption", category: "data_protection", description: "PII encrypted at rest", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "ISO18-004", title: "Breach Notification Process", category: "incident_response", description: "PII breach notification workflow", automation_status: "automated", test_key: "check_breach_notification_sla" },
    ],
    mappings: {
      "A.7.1": ["ISO18-001"], "A.7.2": ["ISO18-001"], "A.7.3": ["ISO18-001"], "A.9.1": ["ISO18-002"],
      "A.10.1": ["ISO18-003"], "A.11.1": ["ISO18-004"],
    },
  },
  {
    code: "ISO27701",
    name: "ISO/IEC 27701 — Privacy Information Management",
    version: "2019",
    jurisdiction: "global",
    authority: "ISO/IEC",
    description: "Extension to ISO 27001 for privacy information management (PIMS).",
    requirements: [
      { requirement_id: "6.1", title: "PII Controller Privacy Policy", category: "compliance", is_mandatory: true },
      { requirement_id: "6.2", title: "PII Processing Purposes", category: "compliance", is_mandatory: true },
      { requirement_id: "6.4", title: "PII Sharing, Transfer, and Disclosure", category: "compliance", is_mandatory: true },
      { requirement_id: "7.1", title: "PII Processor Relationship", category: "compliance", is_mandatory: true },
      { requirement_id: "7.3", title: "PII Processing Instructions", category: "compliance", is_mandatory: true },
      { requirement_id: "8.1", title: "PII Impact Assessment", category: "risk_management", is_mandatory: true },
    ],
    controls: [
      { control_id: "ISO77-001", title: "Privacy Policy Published", category: "compliance", description: "Privacy policy publicly available", automation_status: "manual", test_key: null },
      { control_id: "ISO77-002", title: "ROPA Maintained", category: "compliance", description: "Records of processing activities", automation_status: "manual", test_key: null },
      { control_id: "ISO77-003", title: "PIA/DPIA Process", category: "risk_management", description: "Privacy impact assessment process", automation_status: "manual", test_key: null },
      { control_id: "ISO77-004", title: "Cross-Border Transfer Controls", category: "compliance", description: "Adequacy assessment for transfers", automation_status: "manual", test_key: null },
    ],
    mappings: {
      "6.1": ["ISO77-001"], "6.2": ["ISO77-002"], "6.4": ["ISO77-004"], "7.1": ["ISO77-002"],
      "7.3": ["ISO77-002"], "8.1": ["ISO77-003"],
    },
  },
  {
    code: "ISO22301",
    name: "ISO 22301 — Business Continuity",
    version: "2019",
    jurisdiction: "global",
    authority: "ISO/IEC",
    description: "Business continuity management systems requirements.",
    requirements: [
      { requirement_id: "8.1", title: "Business Impact Analysis", category: "business_continuity", is_mandatory: true },
      { requirement_id: "8.2", title: "Risk Assessment", category: "risk_management", is_mandatory: true },
      { requirement_id: "8.3", title: "Business Continuity Strategy", category: "business_continuity", is_mandatory: true },
      { requirement_id: "8.4", title: "BC Plan", category: "business_continuity", is_mandatory: true },
      { requirement_id: "8.5", title: "Exercise and Testing", category: "business_continuity", is_mandatory: true },
    ],
    controls: [
      { control_id: "BC-001", title: "BIA Conducted Annually", category: "business_continuity", description: "Annual business impact analysis", automation_status: "manual", test_key: null },
      { control_id: "BC-002", title: "BCP Documented and Tested", category: "business_continuity", description: "Business continuity plan tested annually", automation_status: "manual", test_key: null },
      { control_id: "BC-003", title: "Backup and DR Tested", category: "business_continuity", description: "Quarterly DR exercise", automation_status: "automated", test_key: "check_backups" },
    ],
    mappings: {
      "8.1": ["BC-001"], "8.2": ["BC-001"], "8.3": ["BC-002"], "8.4": ["BC-002"], "8.5": ["BC-002", "BC-003"],
    },
  },
  {
    code: "NIST_800_53",
    name: "NIST SP 800-53",
    version: "Rev 5",
    jurisdiction: "us",
    authority: "NIST",
    description: "Security and privacy controls for federal information systems.",
    requirements: [
      { requirement_id: "AC-2", title: "Account Management", category: "access_control", is_mandatory: true },
      { requirement_id: "AC-3", title: "Access Enforcement", category: "access_control", is_mandatory: true },
      { requirement_id: "AU-2", title: "Event Logging", category: "security_operations", is_mandatory: true },
      { requirement_id: "AU-6", title: "Audit Record Review", category: "security_operations", is_mandatory: true },
      { requirement_id: "CA-7", title: "Continuous Monitoring", category: "security_operations", is_mandatory: true },
      { requirement_id: "IA-2", title: "Identification and Authentication", category: "access_control", is_mandatory: true },
      { requirement_id: "IR-4", title: "Incident Handling", category: "incident_response", is_mandatory: true },
      { requirement_id: "RA-5", title: "Vulnerability Scanning", category: "security_operations", is_mandatory: true },
      { requirement_id: "SC-8", title: "Transmission Confidentiality", category: "data_protection", is_mandatory: true },
      { requirement_id: "SC-28", title: "Protection at Rest", category: "data_protection", is_mandatory: true },
      { requirement_id: "SI-2", title: "Flaw Remediation", category: "security_operations", is_mandatory: true },
      { requirement_id: "SI-4", title: "System Monitoring", category: "security_operations", is_mandatory: true },
    ],
    controls: [
      { control_id: "N53-001", title: "Automated Account Management", category: "access_control", description: "SCIM-based account provisioning/deprovisioning", automation_status: "automated", test_key: "check_account_management" },
      { control_id: "N53-002", title: "MFA Enforcement", category: "access_control", description: "MFA on all accounts", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "N53-003", title: "Centralized Audit Logging", category: "security_operations", description: "SIEM with log aggregation", automation_status: "automated", test_key: "check_siem_config" },
      { control_id: "N53-004", title: "Continuous Control Monitoring", category: "security_operations", description: "Automated control monitoring", automation_status: "automated", test_key: "check_control_monitoring" },
      { control_id: "N53-005", title: "Vulnerability Scanning - Automated", category: "security_operations", description: "Automated vuln scanning with remediation tracking", automation_status: "automated", test_key: "check_vuln_scans" },
      { control_id: "N53-006", title: "Encryption at Rest and in Transit", category: "data_protection", description: "FIPS-validated encryption", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "N53-007", title: "Patch Management SLA", category: "security_operations", description: "Patching within SLA based on severity", automation_status: "automated", test_key: "check_patch_sla" },
      { control_id: "N53-008", title: "IDS/IPS Deployed", category: "security_operations", description: "Network and host-based IDS/IPS", automation_status: "automated", test_key: "check_ids_ips" },
    ],
    mappings: {
      "AC-2": ["N53-001"], "AC-3": ["N53-002"], "AU-2": ["N53-003"], "AU-6": ["N53-003"],
      "CA-7": ["N53-004"], "IA-2": ["N53-002"], "IR-4": ["N53-004"], "RA-5": ["N53-005"],
      "SC-8": ["N53-006"], "SC-28": ["N53-006"], "SI-2": ["N53-007"], "SI-4": ["N53-008"],
    },
  },
  {
    code: "NIST_800_171",
    name: "NIST SP 800-171 (CUI)",
    version: "Rev 2",
    jurisdiction: "us",
    authority: "NIST",
    description: "Protecting Controlled Unclassified Information in nonfederal systems.",
    requirements: [
      { requirement_id: "3.1.1", title: "Limit System Access to Authorized Users", category: "access_control", is_mandatory: true },
      { requirement_id: "3.1.2", title: "Limit System Access to Types of Transactions", category: "access_control", is_mandatory: true },
      { requirement_id: "3.3.1", title: "Audit Monitoring and Review", category: "security_operations", is_mandatory: true },
      { requirement_id: "3.5.1", title: "Identify System Users", category: "access_control", is_mandatory: true },
      { requirement_id: "3.5.3", title: "Multi-Factor Authentication", category: "access_control", is_mandatory: true },
      { requirement_id: "3.7.1", title: "Vulnerability Scanning", category: "security_operations", is_mandatory: true },
      { requirement_id: "3.11.2", title: "Remediate Vulnerabilities", category: "security_operations", is_mandatory: true },
      { requirement_id: "3.13.8", title: "Encrypt CUI at Rest", category: "data_protection", is_mandatory: true },
      { requirement_id: "3.13.11", title: "Encrypt CUI in Transit", category: "data_protection", is_mandatory: true },
    ],
    controls: [
      { control_id: "N171-001", title: "CUI Access Controls", category: "access_control", description: "RBAC for CUI systems", automation_status: "automated", test_key: "check_rbac" },
      { control_id: "N171-002", title: "MFA for CUI Access", category: "access_control", description: "MFA on all CUI-accessible systems", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "N171-003", title: "CUI Audit Logging", category: "security_operations", description: "Audit logs for CUI access", automation_status: "automated", test_key: "check_log_retention" },
      { control_id: "N171-004", title: "CUI Vulnerability Scanning", category: "security_operations", description: "Monthly vuln scans on CUI systems", automation_status: "automated", test_key: "check_vuln_scans" },
      { control_id: "N171-005", title: "CUI Encryption at Rest", category: "data_protection", description: "FIPS 140-2 encryption for CUI", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "N171-006", title: "TLS for CUI Transmission", category: "data_protection", description: "TLS 1.2+ for CUI in transit", automation_status: "automated", test_key: "check_tls_config" },
    ],
    mappings: {
      "3.1.1": ["N171-001"], "3.1.2": ["N171-001"], "3.3.1": ["N171-003"], "3.5.1": ["N171-002"],
      "3.5.3": ["N171-002"], "3.7.1": ["N171-004"], "3.11.2": ["N171-004"], "3.13.8": ["N171-005"], "3.13.11": ["N171-006"],
    },
  },
  {
    code: "FedRAMP",
    name: "FedRAMP",
    version: "Rev 4",
    jurisdiction: "us",
    authority: "GSA",
    description: "Federal Risk and Authorization Management Program for cloud services.",
    requirements: [
      { requirement_id: "AC-2(1)", title: "Automated Account Management", category: "access_control", is_mandatory: true },
      { requirement_id: "AC-2(2)", title: "Account Removal", category: "access_control", is_mandatory: true },
      { requirement_id: "AU-6(1)", title: "Audit Record Review and Analysis", category: "security_operations", is_mandatory: true },
      { requirement_id: "IA-2(1)", title: "MFA for Privileged Accounts", category: "access_control", is_mandatory: true },
      { requirement_id: "IA-2(2)", title: "MFA for Non-Privileged Network Access", category: "access_control", is_mandatory: true },
      { requirement_id: "SC-8(1)", title: "Cryptographic Protection During Transmission", category: "data_protection", is_mandatory: true },
      { requirement_id: "SI-2(2)", title: "Automated Flaw Remediation", category: "security_operations", is_mandatory: true },
    ],
    controls: [
      { control_id: "FR-001", title: "Automated Account Lifecycle", category: "access_control", description: "SCIM automated provisioning", automation_status: "automated", test_key: "check_account_management" },
      { control_id: "FR-002", title: "MFA on All Accounts", category: "access_control", description: "MFA for all access including non-privileged", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "FR-003", title: "SIEM with Automated Analysis", category: "security_operations", description: "SIEM with automated log analysis", automation_status: "automated", test_key: "check_siem_config" },
      { control_id: "FR-004", title: "FIPS-Validated Encryption", category: "data_protection", description: "FIPS 140-2 validated crypto", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "FR-005", title: "Automated Patch Management", category: "security_operations", description: "Automated patch deployment", automation_status: "automated", test_key: "check_patch_sla" },
    ],
    mappings: {
      "AC-2(1)": ["FR-001"], "AC-2(2)": ["FR-001"], "AU-6(1)": ["FR-003"], "IA-2(1)": ["FR-002"],
      "IA-2(2)": ["FR-002"], "SC-8(1)": ["FR-004"], "SI-2(2)": ["FR-005"],
    },
  },
  {
    code: "CMMC",
    name: "CMMC (Cybersecurity Maturity Model Certification)",
    version: "2.0",
    jurisdiction: "us",
    authority: "DoD",
    description: "Department of Defense cybersecurity certification for contractors.",
    requirements: [
      { requirement_id: "L2-AC.1", title: "Account Management (Level 2)", category: "access_control", is_mandatory: true },
      { requirement_id: "L2-IA.1", title: "Identification and Authentication (Level 2)", category: "access_control", is_mandatory: true },
      { requirement_id: "L2-SC.1", title: "System and Communications Protection (Level 2)", category: "data_protection", is_mandatory: true },
      { requirement_id: "L3-IR.1", title: "Incident Response (Level 3)", category: "incident_response", is_mandatory: true },
    ],
    controls: [
      { control_id: "CMMC-001", title: "Account Management - Automated", category: "access_control", description: "Automated account provisioning/deprovisioning", automation_status: "automated", test_key: "check_account_management" },
      { control_id: "CMMC-002", title: "MFA Enforcement", category: "access_control", description: "MFA on all accounts", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "CMMC-003", title: "CUI Encryption", category: "data_protection", description: "FIPS encryption for CUI", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "CMMC-004", title: "Incident Response Plan", category: "incident_response", description: "Documented and tested IR plan", automation_status: "manual", test_key: null },
    ],
    mappings: {
      "L2-AC.1": ["CMMC-001"], "L2-IA.1": ["CMMC-002"], "L2-SC.1": ["CMMC-003"], "L3-IR.1": ["CMMC-004"],
    },
  },
  {
    code: "CIS",
    name: "CIS Controls v8",
    version: "v8",
    jurisdiction: "global",
    authority: "Center for Internet Security",
    description: "18 critical security controls for cyber defense.",
    requirements: [
      { requirement_id: "CIS-1", title: "Inventory and Control of Enterprise Assets", category: "asset_management", is_mandatory: true },
      { requirement_id: "CIS-2", title: "Inventory and Control of Software Assets", category: "asset_management", is_mandatory: true },
      { requirement_id: "CIS-3", title: "Data Protection", category: "data_protection", is_mandatory: true },
      { requirement_id: "CIS-4", title: "Secure Configuration of Enterprise Assets and Software", category: "change_management", is_mandatory: true },
      { requirement_id: "CIS-5", title: "Account Management", category: "access_control", is_mandatory: true },
      { requirement_id: "CIS-6", title: "Access Control Management", category: "access_control", is_mandatory: true },
      { requirement_id: "CIS-7", title: "Continuous Vulnerability Management", category: "security_operations", is_mandatory: true },
      { requirement_id: "CIS-8", title: "Audit Log Management", category: "security_operations", is_mandatory: true },
      { requirement_id: "CIS-9", title: "Email and Web Browser Protections", category: "security_operations", is_mandatory: true },
      { requirement_id: "CIS-10", title: "Malware Defenses", category: "security_operations", is_mandatory: true },
      { requirement_id: "CIS-11", title: "Data Recovery", category: "business_continuity", is_mandatory: true },
      { requirement_id: "CIS-12", title: "Network Infrastructure Management", category: "network_security", is_mandatory: true },
      { requirement_id: "CIS-13", title: "Network Monitoring and Defense", category: "security_operations", is_mandatory: true },
      { requirement_id: "CIS-14", title: "Security Awareness and Skills Training", category: "human_resources", is_mandatory: true },
      { requirement_id: "CIS-17", title: "Incident Response Management", category: "incident_response", is_mandatory: true },
      { requirement_id: "CIS-18", title: "Penetration Testing", category: "security_operations", is_mandatory: true },
    ],
    controls: [
      { control_id: "CIS-001", title: "Automated Asset Discovery", category: "asset_management", description: "Continuous asset discovery and inventory", automation_status: "automated", test_key: "check_asset_inventory" },
      { control_id: "CIS-002", title: "Software Inventory - Automated", category: "asset_management", description: "Automated software inventory", automation_status: "automated", test_key: "check_software_inventory" },
      { control_id: "CIS-003", title: "Data Classification and Encryption", category: "data_protection", description: "Data classification with encryption", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "CIS-004", title: "CIS Benchmarks Enforced", category: "change_management", description: "CIS hardening baselines", automation_status: "automated", test_key: "check_cis_baselines" },
      { control_id: "CIS-005", title: "Account Lifecycle - Automated", category: "access_control", description: "Automated account management", automation_status: "automated", test_key: "check_account_management" },
      { control_id: "CIS-006", title: "MFA and RBAC", category: "access_control", description: "MFA + role-based access", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "CIS-007", title: "Vulnerability Scanning - Continuous", category: "security_operations", description: "Continuous vuln scanning", automation_status: "automated", test_key: "check_vuln_scans" },
      { control_id: "CIS-008", title: "Centralized Logging (SIEM)", category: "security_operations", description: "SIEM with log aggregation", automation_status: "automated", test_key: "check_siem_config" },
      { control_id: "CIS-010", title: "EDR on All Endpoints", category: "security_operations", description: "EDR deployed everywhere", automation_status: "automated", test_key: "check_edr_coverage" },
      { control_id: "CIS-011", title: "Automated Backups", category: "business_continuity", description: "Automated backup with recovery testing", automation_status: "automated", test_key: "check_backups" },
      { control_id: "CIS-014", title: "Security Training - Annual", category: "human_resources", description: "Annual security awareness training", automation_status: "automated", test_key: "check_training_completion" },
      { control_id: "CIS-017", title: "IR Plan and Playbooks", category: "incident_response", description: "Documented IR with playbooks", automation_status: "manual", test_key: null },
    ],
    mappings: {
      "CIS-1": ["CIS-001"], "CIS-2": ["CIS-002"], "CIS-3": ["CIS-003"], "CIS-4": ["CIS-004"],
      "CIS-5": ["CIS-005"], "CIS-6": ["CIS-006"], "CIS-7": ["CIS-007"], "CIS-8": ["CIS-008"],
      "CIS-9": ["CIS-010"], "CIS-10": ["CIS-010"], "CIS-11": ["CIS-011"], "CIS-12": ["CIS-004"],
      "CIS-13": ["CIS-008"], "CIS-14": ["CIS-014"], "CIS-17": ["CIS-017"], "CIS-18": ["CIS-007"],
    },
  },
  {
    code: "COBIT",
    name: "COBIT 2019",
    version: "2019",
    jurisdiction: "global",
    authority: "ISACA",
    description: "Framework for IT governance and management.",
    requirements: [
      { requirement_id: "EDM01", title: "Ensure Governance Framework Setting", category: "compliance", is_mandatory: true },
      { requirement_id: "EDM02", title: "Ensure Benefits Delivery", category: "compliance", is_mandatory: true },
      { requirement_id: "EDM03", title: "Ensure Risk Optimization", category: "risk_management", is_mandatory: true },
      { requirement_id: "APO12", title: "Manage Risk", category: "risk_management", is_mandatory: true },
      { requirement_id: "APO13", title: "Manage Security", category: "security_operations", is_mandatory: true },
      { requirement_id: "BAI06", title: "Manage Changes", category: "change_management", is_mandatory: true },
      { requirement_id: "DSS05", title: "Manage Security Services", category: "security_operations", is_mandatory: true },
      { requirement_id: "MEA02", title: "Monitor System and Performance", category: "security_operations", is_mandatory: true },
    ],
    controls: [
      { control_id: "COB-001", title: "IT Governance Framework", category: "compliance", description: "Documented IT governance framework", automation_status: "manual", test_key: null },
      { control_id: "COB-002", title: "Risk Management Process", category: "risk_management", description: "Formal risk management process", automation_status: "manual", test_key: null },
      { control_id: "COB-003", title: "Change Management Process", category: "change_management", description: "Formal change management with approvals", automation_status: "automated", test_key: "check_change_management" },
      { control_id: "COB-004", title: "Security Operations Center", category: "security_operations", description: "SOC with monitoring and response", automation_status: "automated", test_key: "check_siem_config" },
    ],
    mappings: {
      "EDM01": ["COB-001"], "EDM02": ["COB-001"], "EDM03": ["COB-002"], "APO12": ["COB-002"],
      "APO13": ["COB-004"], "BAI06": ["COB-003"], "DSS05": ["COB-004"], "MEA02": ["COB-004"],
    },
  },
  {
    code: "COSO_ERM",
    name: "COSO ERM",
    version: "2017",
    jurisdiction: "global",
    authority: "COSO",
    description: "Enterprise Risk Management — integrating with strategy and performance.",
    requirements: [
      { requirement_id: "GD-1", title: "Governance and Culture", category: "compliance", is_mandatory: true },
      { requirement_id: "SP-1", title: "Strategy and Objective Setting", category: "risk_management", is_mandatory: true },
      { requirement_id: "PE-1", title: "Performance", category: "risk_management", is_mandatory: true },
      { requirement_id: "RV-1", title: "Review and Revision", category: "risk_management", is_mandatory: true },
      { requirement_id: "IF-1", title: "Information, Communication, and Reporting", category: "compliance", is_mandatory: true },
    ],
    controls: [
      { control_id: "COSO-001", title: "ERM Framework Documented", category: "risk_management", description: "Enterprise risk management framework", automation_status: "manual", test_key: null },
      { control_id: "COSO-002", title: "Risk Register Maintained", category: "risk_management", description: "Centralized risk register", automation_status: "manual", test_key: null },
      { control_id: "COSO-003", title: "Risk Reporting to Board", category: "compliance", description: "Regular risk reporting to board", automation_status: "manual", test_key: null },
    ],
    mappings: {
      "GD-1": ["COSO-001"], "SP-1": ["COSO-002"], "PE-1": ["COSO-002"], "RV-1": ["COSO-002"], "IF-1": ["COSO-003"],
    },
  },
  {
    code: "KING_IV",
    name: "King IV Report on Corporate Governance",
    version: "2016",
    jurisdiction: "za",
    authority: "Institute of Directors Southern Africa",
    description: "South African corporate governance code.",
    requirements: [
      { requirement_id: "Principle 1", title: "Ethical Leadership and Corporate Citizenship", category: "compliance", is_mandatory: true },
      { requirement_id: "Principle 5", title: "Governing Body Comprises Requisite Balance", category: "compliance", is_mandatory: true },
      { requirement_id: "Principle 9", title: "Leadership and Culture of Risk Management", category: "risk_management", is_mandatory: true },
      { requirement_id: "Principle 11", title: "Governing Body Responsible for IT Governance", category: "compliance", is_mandatory: true },
      { requirement_id: "Principle 13", title: "Compliance with Laws and Regulations", category: "compliance", is_mandatory: true },
      { requirement_id: "Principle 14", title: "Remuneration Committee", category: "compliance", is_mandatory: true },
    ],
    controls: [
      { control_id: "K4-001", title: "Board Charter and Ethics Policy", category: "compliance", description: "Board charter with ethics provisions", automation_status: "manual", test_key: null },
      { control_id: "K4-002", title: "Risk Committee Charter", category: "risk_management", description: "Risk committee with documented charter", automation_status: "manual", test_key: null },
      { control_id: "K4-003", title: "IT Governance Charter", category: "compliance", description: "IT governance framework approved by board", automation_status: "manual", test_key: null },
      { control_id: "K4-004", title: "Compliance Register", category: "compliance", description: "Regulatory compliance register", automation_status: "manual", test_key: null },
    ],
    mappings: {
      "Principle 1": ["K4-001"], "Principle 5": ["K4-001"], "Principle 9": ["K4-002"],
      "Principle 11": ["K4-003"], "Principle 13": ["K4-004"], "Principle 14": ["K4-001"],
    },
  },
  {
    code: "SADC",
    name: "SADC Model Law on Data Protection",
    version: "2013",
    jurisdiction: "sadc",
    authority: "SADC Secretariat",
    description: "Southern African Development Community data protection model law.",
    requirements: [
      { requirement_id: "Art. 8", title: "Lawful Processing", category: "compliance", is_mandatory: true },
      { requirement_id: "Art. 10", title: "Data Quality", category: "data_protection", is_mandatory: true },
      { requirement_id: "Art. 11", title: "Data Security", category: "data_protection", is_mandatory: true },
      { requirement_id: "Art. 12", title: "Data Subject Rights", category: "compliance", is_mandatory: true },
      { requirement_id: "Art. 14", title: "Notification of Breach", category: "incident_response", is_mandatory: true },
      { requirement_id: "Art. 16", title: "Cross-Border Transfer", category: "compliance", is_mandatory: true },
      { requirement_id: "Art. 22", title: "Data Protection Authority", category: "compliance", is_mandatory: true },
    ],
    controls: [
      { control_id: "SADC-001", title: "Data Protection Register", category: "compliance", description: "Register of processing activities", automation_status: "manual", test_key: null },
      { control_id: "SADC-002", title: "Encryption and Access Controls", category: "data_protection", description: "Technical safeguards", automation_status: "automated", test_key: "check_encryption_at_rest" },
      { control_id: "SADC-003", title: "Breach Notification Process", category: "incident_response", description: "Breach notification to authority", automation_status: "automated", test_key: "check_breach_notification_sla" },
      { control_id: "SADC-004", title: "Cross-Border Transfer Assessment", category: "compliance", description: "Adequacy assessment for transfers", automation_status: "manual", test_key: null },
    ],
    mappings: {
      "Art. 8": ["SADC-001"], "Art. 10": ["SADC-001"], "Art. 11": ["SADC-002"], "Art. 12": ["SADC-001"],
      "Art. 14": ["SADC-003"], "Art. 16": ["SADC-004"], "Art. 22": ["SADC-001"],
    },
  },
  {
    code: "CSA_STAR",
    name: "CSA STAR (Security, Trust, Assurance, Risk)",
    version: "v2",
    jurisdiction: "global",
    authority: "Cloud Security Alliance",
    description: "Cloud security certification program.",
    requirements: [
      { requirement_id: "Consensus Assessments-1", title: "Cloud Controls Matrix Assessment", category: "compliance", is_mandatory: true },
      { requirement_id: "Consensus Assessments-2", title: "Continuous Monitoring", category: "security_operations", is_mandatory: true },
      { requirement_id: "Consensus Assessments-3", title: "Independent Audit", category: "compliance", is_mandatory: true },
    ],
    controls: [
      { control_id: "CSA-001", title: "CCM Assessment Completed", category: "compliance", description: "Cloud Controls Matrix self-assessment", automation_status: "manual", test_key: null },
      { control_id: "CSA-002", title: "Continuous Cloud Monitoring", category: "security_operations", description: "CSPM with continuous monitoring", automation_status: "automated", test_key: "check_cloud_monitoring" },
    ],
    mappings: {
      "Consensus Assessments-1": ["CSA-001"], "Consensus Assessments-2": ["CSA-002"], "Consensus Assessments-3": ["CSA-001"],
    },
  },
  {
    code: "TISAX",
    name: "TISAX (Trusted Information Security Assessment Exchange)",
    version: "5.1",
    jurisdiction: "eu",
    authority: "ENX",
    description: "Automotive industry information security assessment.",
    requirements: [
      { requirement_id: "IS-001", title: "Information Security Management", category: "compliance", is_mandatory: true },
      { requirement_id: "IS-002", title: "Asset Management", category: "asset_management", is_mandatory: true },
      { requirement_id: "IS-003", title: "Human Resources Security", category: "human_resources", is_mandatory: true },
      { requirement_id: "IS-004", title: "Physical Security", category: "physical_security", is_mandatory: true },
      { requirement_id: "IS-005", title: "Access Control", category: "access_control", is_mandatory: true },
      { requirement_id: "IS-006", title: "Cryptography", category: "data_protection", is_mandatory: true },
    ],
    controls: [
      { control_id: "TISAX-001", title: "ISMS Documented (ISO 27001)", category: "compliance", description: "ISO 27001-based ISMS", automation_status: "manual", test_key: null },
      { control_id: "TISAX-002", title: "MFA and Access Controls", category: "access_control", description: "MFA + RBAC", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "TISAX-003", title: "Encryption at Rest and in Transit", category: "data_protection", description: "Strong encryption enforced", automation_status: "automated", test_key: "check_encryption_at_rest" },
    ],
    mappings: {
      "IS-001": ["TISAX-001"], "IS-002": ["TISAX-001"], "IS-003": ["TISAX-001"], "IS-004": ["TISAX-002"],
      "IS-005": ["TISAX-002"], "IS-006": ["TISAX-003"],
    },
  },
  {
    code: "CYBER_ESSENTIALS",
    name: "Cyber Essentials (UK)",
    version: "2023",
    jurisdiction: "uk",
    authority: "NCSC (UK)",
    description: "UK government-backed cybersecurity certification scheme.",
    requirements: [
      { requirement_id: "CE-1", title: "Firewalls and Internet Gateways", category: "network_security", is_mandatory: true },
      { requirement_id: "CE-2", title: "Secure Configuration", category: "change_management", is_mandatory: true },
      { requirement_id: "CE-3", title: "User Access Control", category: "access_control", is_mandatory: true },
      { requirement_id: "CE-4", title: "Malware Protection", category: "security_operations", is_mandatory: true },
      { requirement_id: "CE-5", title: "Patch Management", category: "security_operations", is_mandatory: true },
    ],
    controls: [
      { control_id: "CE-001", title: "Firewall Configurations Reviewed", category: "network_security", description: "Firewall rules documented and reviewed", automation_status: "automated", test_key: "check_firewall_config" },
      { control_id: "CE-002", title: "Secure Config Baselines", category: "change_management", description: "Hardening baselines applied", automation_status: "automated", test_key: "check_cis_baselines" },
      { control_id: "CE-003", title: "MFA and RBAC", category: "access_control", description: "MFA + least privilege", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "CE-004", title: "EDR/Anti-Malware", category: "security_operations", description: "Malware protection on all endpoints", automation_status: "automated", test_key: "check_edr_coverage" },
      { control_id: "CE-005", title: "Patching Within 14 Days", category: "security_operations", description: "Critical patches within 14 days", automation_status: "automated", test_key: "check_patch_sla" },
    ],
    mappings: {
      "CE-1": ["CE-001"], "CE-2": ["CE-002"], "CE-3": ["CE-003"], "CE-4": ["CE-004"], "CE-5": ["CE-005"],
    },
  },
  {
    code: "APRA_CPS234",
    name: "APRA CPS 234 (Australia)",
    version: "2020",
    jurisdiction: "au",
    authority: "APRA",
    description: "Australian Prudential Standard on information security.",
    requirements: [
      { requirement_id: "CPS234-1", title: "Information Security Capability", category: "security_operations", is_mandatory: true },
      { requirement_id: "CPS234-2", title: "Implementation of Controls", category: "security_operations", is_mandatory: true },
      { requirement_id: "CPS234-3", title: "Incident Notification", category: "incident_response", is_mandatory: true },
      { requirement_id: "CPS234-4", title: "Control Testing", category: "security_operations", is_mandatory: true },
      { requirement_id: "CPS234-5", title: "Internal Review", category: "compliance", is_mandatory: true },
    ],
    controls: [
      { control_id: "APRA-001", title: "Information Security Capability Assessment", category: "security_operations", description: "Annual IS capability assessment", automation_status: "manual", test_key: null },
      { control_id: "APRA-002", title: "Security Controls Implemented", category: "security_operations", description: "Controls commensurate with threats", automation_status: "automated", test_key: "check_control_monitoring" },
      { control_id: "APRA-003", title: "72-Hour Incident Notification", category: "incident_response", description: "Notify APRA within 72 hours", automation_status: "automated", test_key: "check_breach_notification_sla" },
      { control_id: "APRA-004", title: "Control Testing - Annual", category: "security_operations", description: "Annual control effectiveness testing", automation_status: "automated", test_key: "check_control_monitoring" },
    ],
    mappings: {
      "CPS234-1": ["APRA-001"], "CPS234-2": ["APRA-002"], "CPS234-3": ["APRA-003"], "CPS234-4": ["APRA-004"], "CPS234-5": ["APRA-004"],
    },
  },
  {
    code: "NYDFS",
    name: "NYDFS 23 NYCRR 500",
    version: "2023",
    jurisdiction: "us",
    authority: "NY Department of Financial Services",
    description: "Cybersecurity regulation for financial services companies.",
    requirements: [
      { requirement_id: "500.2", title: "Cybersecurity Program", category: "security_operations", is_mandatory: true },
      { requirement_id: "500.3", title: "Cybersecurity Policy", category: "compliance", is_mandatory: true },
      { requirement_id: "500.5", title: "CISO Designation", category: "compliance", is_mandatory: true },
      { requirement_id: "500.6", title: "Multi-Factor Authentication", category: "access_control", is_mandatory: true },
      { requirement_id: "500.7", title: "Access Privileges", category: "access_control", is_mandatory: true },
      { requirement_id: "500.8", title: "Application Security", category: "change_management", is_mandatory: true },
      { requirement_id: "500.11", title: "Third-Party Service Provider Security", category: "compliance", is_mandatory: true },
      { requirement_id: "500.14", title: "Training and Monitoring", category: "human_resources", is_mandatory: true },
      { requirement_id: "500.16", title: "Incident Response Plan", category: "incident_response", is_mandatory: true },
      { requirement_id: "500.17", title: "Notices to Superintendent", category: "incident_response", is_mandatory: true },
    ],
    controls: [
      { control_id: "NYDFS-001", title: "Cybersecurity Program Documented", category: "security_operations", description: "Risk-based cybersecurity program", automation_status: "manual", test_key: null },
      { control_id: "NYDFS-002", title: "MFA on All Systems", category: "access_control", description: "MFA enforced globally", automation_status: "automated", test_key: "check_mfa_enabled" },
      { control_id: "NYDFS-003", title: "RBAC and Least Privilege", category: "access_control", description: "Access based on need-to-know", automation_status: "automated", test_key: "check_rbac" },
      { control_id: "NYDFS-004", title: "Secure SDLC", category: "change_management", description: "Application security in development", automation_status: "automated", test_key: "check_devsecops_pipeline" },
      { control_id: "NYDFS-005", title: "Third-Party Risk Management", category: "compliance", description: "Vendor security assessments", automation_status: "manual", test_key: null },
      { control_id: "NYDFS-006", title: "72-Hour Breach Notification", category: "incident_response", description: "Notify DFS within 72 hours", automation_status: "automated", test_key: "check_breach_notification_sla" },
    ],
    mappings: {
      "500.2": ["NYDFS-001"], "500.3": ["NYDFS-001"], "500.5": ["NYDFS-001"], "500.6": ["NYDFS-002"],
      "500.7": ["NYDFS-003"], "500.8": ["NYDFS-004"], "500.11": ["NYDFS-005"], "500.14": ["NYDFS-001"],
      "500.16": ["NYDFS-006"], "500.17": ["NYDFS-006"],
    },
  },
  {
    code: "ISO42001",
    name: "ISO/IEC 42001 — AI Management System",
    version: "2023",
    jurisdiction: "global",
    authority: "ISO/IEC",
    description: "AI management system standard for responsible AI development.",
    requirements: [
      { requirement_id: "5.1", title: "AI Policy", category: "compliance", is_mandatory: true },
      { requirement_id: "6.1", title: "AI Risk Assessment", category: "risk_management", is_mandatory: true },
      { requirement_id: "7.1", title: "AI System Inventory", category: "asset_management", is_mandatory: true },
      { requirement_id: "8.1", title: "AI System Development Controls", category: "change_management", is_mandatory: true },
      { requirement_id: "8.2", title: "AI Data Quality Controls", category: "data_protection", is_mandatory: true },
      { requirement_id: "8.3", title: "AI Bias Testing", category: "compliance", is_mandatory: true },
      { requirement_id: "9.1", title: "AI Performance Monitoring", category: "security_operations", is_mandatory: true },
    ],
    controls: [
      { control_id: "AI-001", title: "AI Governance Policy", category: "compliance", description: "AI usage and governance policy", automation_status: "manual", test_key: null },
      { control_id: "AI-002", title: "AI Risk Assessment Process", category: "risk_management", description: "AI-specific risk assessment", automation_status: "manual", test_key: null },
      { control_id: "AI-003", title: "AI System Inventory", category: "asset_management", description: "Inventory of all AI systems and models", automation_status: "manual", test_key: null },
      { control_id: "AI-004", title: "AI Bias and Fairness Testing", category: "compliance", description: "Regular bias testing of AI models", automation_status: "manual", test_key: null },
      { control_id: "AI-005", title: "AI Output Monitoring", category: "security_operations", description: "Monitoring of AI outputs for anomalies", automation_status: "automated", test_key: "check_ai_monitoring" },
    ],
    mappings: {
      "5.1": ["AI-001"], "6.1": ["AI-002"], "7.1": ["AI-003"], "8.1": ["AI-001"],
      "8.2": ["AI-004"], "8.3": ["AI-004"], "9.1": ["AI-005"],
    },
  },
  {
    code: "DORA",
    name: "DORA (Digital Operational Resilience Act)",
    version: "2024",
    jurisdiction: "eu",
    authority: "European Commission",
    description: "EU regulation on digital operational resilience for financial entities.",
    requirements: [
      { requirement_id: "Art. 5", title: "ICT Risk Management Framework", category: "risk_management", is_mandatory: true },
      { requirement_id: "Art. 6", title: "ICT Risk Identification", category: "risk_management", is_mandatory: true },
      { requirement_id: "Art. 9", title: "Protection and Prevention", category: "security_operations", is_mandatory: true },
      { requirement_id: "Art. 10", title: "ICT-Related Incident Management", category: "incident_response", is_mandatory: true },
      { requirement_id: "Art. 11", title: "Digital Operational Resilience Testing", category: "security_operations", is_mandatory: true },
      { requirement_id: "Art. 25", title: "ICT Third-Party Risk", category: "compliance", is_mandatory: true },
      { requirement_id: "Art. 26", title: "Third-Party Risk Strategy", category: "compliance", is_mandatory: true },
    ],
    controls: [
      { control_id: "DORA-001", title: "ICT Risk Management Framework", category: "risk_management", description: "Documented ICT risk framework", automation_status: "manual", test_key: null },
      { control_id: "DORA-002", title: "ICT Incident Management Process", category: "incident_response", description: "ICT incident classification and response", automation_status: "automated", test_key: "check_breach_notification_sla" },
      { control_id: "DORA-003", title: "Resilience Testing - Annual", category: "security_operations", description: "Annual operational resilience testing", automation_status: "manual", test_key: null },
      { control_id: "DORA-004", title: "ICT Third-Party Register", category: "compliance", description: "Register of all ICT third parties", automation_status: "manual", test_key: null },
      { control_id: "DORA-005", title: "Vulnerability Scanning - Continuous", category: "security_operations", description: "Continuous vulnerability management", automation_status: "automated", test_key: "check_vuln_scans" },
    ],
    mappings: {
      "Art. 5": ["DORA-001"], "Art. 6": ["DORA-001"], "Art. 9": ["DORA-005"], "Art. 10": ["DORA-002"],
      "Art. 11": ["DORA-003"], "Art. 25": ["DORA-004"], "Art. 26": ["DORA-004"],
    },
  },
  {
    code: "NIS2",
    name: "NIS2 Directive (EU)",
    version: "2022",
    jurisdiction: "eu",
    authority: "European Commission",
    description: "EU Network and Information Security Directive — critical infrastructure.",
    requirements: [
      { requirement_id: "Art. 21", title: "Risk Management Measures", category: "risk_management", is_mandatory: true },
      { requirement_id: "Art. 21(2)a", title: "Incident Handling", category: "incident_response", is_mandatory: true },
      { requirement_id: "Art. 21(2)b", title: "Business Continuity", category: "business_continuity", is_mandatory: true },
      { requirement_id: "Art. 21(2)c", title: "Supply Chain Security", category: "compliance", is_mandatory: true },
      { requirement_id: "Art. 21(2)d", title: "Network Security", category: "network_security", is_mandatory: true },
      { requirement_id: "Art. 21(2)e", title: "Access Control", category: "access_control", is_mandatory: true },
      { requirement_id: "Art. 23", title: "Incident Reporting (24h/72h)", category: "incident_response", is_mandatory: true },
    ],
    controls: [
      { control_id: "NIS2-001", title: "Risk Management Framework", category: "risk_management", description: "Documented risk management measures", automation_status: "manual", test_key: null },
      { control_id: "NIS2-002", title: "Incident Response and Reporting", category: "incident_response", description: "24-hour early warning + 72-hour notification", automation_status: "automated", test_key: "check_breach_notification_sla" },
      { control_id: "NIS2-003", title: "BCP and DR", category: "business_continuity", description: "Business continuity and disaster recovery", automation_status: "automated", test_key: "check_backups" },
      { control_id: "NIS2-004", title: "Supply Chain Risk Management", category: "compliance", description: "Third-party security assessments", automation_status: "manual", test_key: null },
      { control_id: "NIS2-005", title: "MFA and Access Controls", category: "access_control", description: "MFA + RBAC", automation_status: "automated", test_key: "check_mfa_enabled" },
    ],
    mappings: {
      "Art. 21": ["NIS2-001"], "Art. 21(2)a": ["NIS2-002"], "Art. 21(2)b": ["NIS2-003"],
      "Art. 21(2)c": ["NIS2-004"], "Art. 21(2)d": ["NIS2-005"], "Art. 21(2)e": ["NIS2-005"], "Art. 23": ["NIS2-002"],
    },
  },
];

export const TEMPLATE_COUNT = FRAMEWORK_TEMPLATES.length;
export const TOTAL_REQUIREMENTS = FRAMEWORK_TEMPLATES.reduce((sum, f) => sum + f.requirements.length, 0);
export const TOTAL_CONTROLS = FRAMEWORK_TEMPLATES.reduce((sum, f) => sum + f.controls.length, 0);
export const TOTAL_MAPPINGS = FRAMEWORK_TEMPLATES.reduce((sum, f) => sum + Object.keys(f.mappings).length, 0);