// Native integration catalog for automated evidence collection
// Drata/Vanta competitive feature — 15 integrations across cloud, identity, code, monitoring, security

export const integrationCategories = {
  cloud: { label: "Cloud Infrastructure", color: "text-orange-600 bg-orange-50" },
  identity: { label: "Identity & Access", color: "text-blue-600 bg-blue-50" },
  code: { label: "Source Code & CI/CD", color: "text-purple-600 bg-purple-50" },
  monitoring: { label: "Monitoring & Logging", color: "text-cyan-600 bg-cyan-50" },
  security: { label: "Security Tools", color: "text-red-600 bg-red-50" },
  productivity: { label: "Productivity & SaaS", color: "text-emerald-600 bg-emerald-50" },
};

export const integrations = [
  {
    id: "gcp",
    name: "Google Cloud Platform",
    category: "cloud",
    icon: "Cloud",
    description: "Evidence from GCP Security Command Center, IAM, and Cloud Audit Logs.",
    evidenceTypes: ["IAM policies", "Security Command Center findings", "Audit logs", "Encryption config"],
    connectionMethod: "Service Account JSON Key",
    status: "available",
    controlsCovered: 12,
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
  },
  {
    id: "azure",
    name: "Microsoft Azure",
    category: "cloud",
    icon: "Cloud",
    description: "Evidence from Azure Security Center, AD, and Activity Logs.",
    evidenceTypes: ["Security Center score", "AD sign-in logs", "Activity logs", "Encryption settings"],
    connectionMethod: "Service Principal (Client ID + Secret)",
    status: "available",
    controlsCovered: 12,
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
  },
  {
    id: "github",
    name: "GitHub",
    category: "code",
    icon: "Github",
    description: "Branch protection, code review, and commit evidence from repositories.",
    evidenceTypes: ["Branch protection rules", "Code review approvals", "Commit history", "Signed commits"],
    connectionMethod: "Personal Access Token / OAuth",
    status: "available",
    controlsCovered: 8,
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "code",
    icon: "Github",
    description: "Merge request approvals, pipeline scans, and access evidence.",
    evidenceTypes: ["Merge request approvals", "Pipeline scan results", "Access logs"],
    connectionMethod: "Personal Access Token",
    status: "available",
    controlsCovered: 6,
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "okta",
    name: "Okta",
    category: "identity",
    icon: "KeyRound",
    description: "User lifecycle, MFA, and access review evidence from Okta.",
    evidenceTypes: ["MFA enrollment", "User lifecycle", "App assignments", "Group memberships"],
    connectionMethod: "API Token",
    status: "available",
    controlsCovered: 10,
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
  },
  {
    id: "google-workspace",
    name: "Google Workspace",
    category: "productivity",
    icon: "Mail",
    description: "Admin console evidence — MFA, user activity, and data access.",
    evidenceTypes: ["MFA enforcement", "User activity logs", "Data access", "Admin actions"],
    connectionMethod: "OAuth / Service Account",
    status: "available",
    controlsCovered: 8,
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365 / Entra ID",
    category: "identity",
    icon: "Mail",
    description: "Conditional access, MFA, and sign-in logs from M365 / Azure AD.",
    evidenceTypes: ["Conditional access policies", "MFA registration", "Sign-in logs", "Audit logs"],
    connectionMethod: "Application (Client ID + Secret)",
    status: "available",
    controlsCovered: 10,
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "monitoring",
    icon: "Activity",
    description: "Infrastructure monitoring, log retention, and alerting evidence.",
    evidenceTypes: ["Log retention config", "Active monitors", "Alert history", "Integration status"],
    connectionMethod: "API Key + App Key",
    status: "available",
    controlsCovered: 6,
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "security",
    icon: "Shield",
    description: "WAF rules, DNS config, and SSL/TLS evidence from Cloudflare.",
    evidenceTypes: ["WAF rule sets", "SSL/TLS config", "DNS records", "Access policies"],
    connectionMethod: "API Token",
    status: "available",
    controlsCovered: 7,
    frameworks: ["SOC 2", "ISO 27001", "PCI DSS"],
  },
  {
    id: "slack",
    name: "Slack",
    category: "productivity",
    icon: "MessageSquare",
    description: "Workspace access logs, MFA, and session management evidence.",
    evidenceTypes: ["Access logs", "MFA enforcement", "Session config", "App integrations"],
    connectionMethod: "OAuth / Bot Token",
    status: "connected",
    controlsCovered: 5,
    frameworks: ["SOC 2"],
  },
  {
    id: "jira",
    name: "Jira",
    category: "code",
    icon: "CheckSquare",
    description: "Issue tracking, sprint evidence, and remediation ticket history.",
    evidenceTypes: ["Issue history", "Sprint reports", "Remediation tickets", "Workflow transitions"],
    connectionMethod: "API Token + Email",
    status: "connected",
    controlsCovered: 4,
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    category: "monitoring",
    icon: "Activity",
    description: "On-call schedules, incident response, and escalation evidence.",
    evidenceTypes: ["On-call schedules", "Incident history", "Escalation policies", "Response times"],
    connectionMethod: "API Token",
    status: "available",
    controlsCovered: 5,
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "1password",
    name: "1Password",
    category: "security",
    icon: "KeyRound",
    description: "Vault access, password policies, and usage evidence.",
    evidenceTypes: ["Vault access logs", "Password policy config", "Item usage", "Team memberships"],
    connectionMethod: "API Token",
    status: "available",
    controlsCovered: 4,
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "code",
    icon: "Rocket",
    description: "Deployment logs, environment variables, and access evidence.",
    evidenceTypes: ["Deployment logs", "Environment config", "Team access", "Project settings"],
    connectionMethod: "Access Token",
    status: "available",
    controlsCovered: 4,
    frameworks: ["SOC 2"],
  },
];

export const getIntegrationsByCategory = () => {
  const grouped = {};
  for (const [key, val] of Object.entries(integrationCategories)) {
    grouped[key] = { ...val, items: integrations.filter((i) => i.category === key) };
  }
  return grouped;
};

export const getConnectedIntegrations = () => integrations.filter((i) => i.status === "connected");
export const getAvailableIntegrations = () => integrations.filter((i) => i.status === "available");