// NIST 800-61 Incident Response Playbooks
// Pre-built automated response chains for common incident types

export const IR_PLAYBOOKS = [
  {
    type: "ransomware",
    label: "Ransomware Response",
    icon: "Lock",
    severity: "critical",
    description: "NIST 800-61 ransomware containment and recovery playbook",
    steps: [
      { phase: "Detection & Analysis", action: "Isolate affected endpoints via EDR", auto: "isolate_endpoint", sla: "0.5h" },
      { phase: "Detection & Analysis", action: "Quarantine encrypted systems from network", auto: "quarantine_network", sla: "1h" },
      { phase: "Detection & Analysis", action: "Preserve forensic evidence (memory + disk images)", auto: "preserve_evidence", sla: "2h" },
      { phase: "Containment", action: "Identify and block C2 domains/IPs at firewall", auto: "block_c2", sla: "2h" },
      { phase: "Containment", action: "Disable compromised user accounts", auto: "disable_accounts", sla: "1h" },
      { phase: "Containment", action: "Revoke active sessions for affected users", auto: "revoke_sessions", sla: "1h" },
      { phase: "Eradication", action: "Scan all endpoints for ransomware payload", auto: "edr_full_scan", sla: "4h" },
      { phase: "Eradication", action: "Patch exploited vulnerability (entry vector)", auto: "create_patch_task", sla: "24h" },
      { phase: "Recovery", action: "Restore systems from clean backup", auto: "restore_backup", sla: "8h" },
      { phase: "Recovery", action: "Verify system integrity post-restore", auto: "verify_integrity", sla: "4h" },
      { phase: "Post-Incident", action: "Generate after-action report", auto: "after_action_report", sla: "72h" },
      { phase: "Post-Incident", action: "Update IR plan with lessons learned", auto: "update_ir_plan", sla: "168h" },
    ],
  },
  {
    type: "data_breach",
    label: "Data Breach Response",
    icon: "ShieldAlert",
    severity: "critical",
    description: "NIST 800-61 data breach containment, notification, and recovery",
    steps: [
      { phase: "Detection & Analysis", action: "Identify scope of exposed data (records, types)", auto: "scope_analysis", sla: "2h" },
      { phase: "Detection & Analysis", action: "Identify attack vector and entry point", auto: "identify_vector", sla: "4h" },
      { phase: "Containment", action: "Revoke compromised credentials and API keys", auto: "revoke_credentials", sla: "1h" },
      { phase: "Containment", action: "Block exfiltration channels (firewall/DLP)", auto: "block_exfiltration", sla: "2h" },
      { phase: "Containment", action: "Preserve evidence (logs, access records)", auto: "preserve_evidence", sla: "4h" },
      { phase: "Notification", action: "Assess regulatory notification requirements (72h GDPR)", auto: "assess_notification", sla: "24h" },
      { phase: "Notification", action: "Notify DPO and legal counsel", auto: "notify_dpo", sla: "4h" },
      { phase: "Notification", action: "Prepare regulator notification (if required)", auto: "prepare_regulator_notice", sla: "48h" },
      { phase: "Notification", action: "Prepare affected individual notification", auto: "prepare_individual_notice", sla: "72h" },
      { phase: "Eradication", action: "Close attack vector and patch systems", auto: "create_patch_task", sla: "24h" },
      { phase: "Recovery", action: "Restore affected systems from backup", auto: "restore_backup", sla: "8h" },
      { phase: "Post-Incident", action: "Generate breach impact report", auto: "breach_impact_report", sla: "168h" },
      { phase: "Post-Incident", action: "Update data protection controls", auto: "update_controls", sla: "168h" },
    ],
  },
  {
    type: "phishing",
    label: "Phishing Response",
    icon: "Mail",
    severity: "high",
    description: "NIST 800-61 phishing containment and user remediation",
    steps: [
      { phase: "Detection & Analysis", action: "Identify all recipients of phishing email", auto: "identify_recipients", sla: "1h" },
      { phase: "Detection & Analysis", action: "Analyze phishing payload (URLs, attachments)", auto: "analyze_payload", sla: "2h" },
      { phase: "Containment", action: "Remove phishing emails from all mailboxes", auto: "purge_emails", sla: "1h" },
      { phase: "Containment", action: "Block sender domain and phishing URLs", auto: "block_sender", sla: "1h" },
      { phase: "Containment", action: "Identify users who clicked (from logs)", auto: "identify_clickers", sla: "2h" },
      { phase: "Containment", action: "Force password reset for affected users", auto: "force_password_reset", sla: "2h" },
      { phase: "Containment", action: "Revoke active sessions for affected users", auto: "revoke_sessions", sla: "1h" },
      { phase: "Containment", action: "Enable MFA for affected users (if not enrolled)", auto: "enable_mfa", sla: "4h" },
      { phase: "Eradication", action: "Scan affected endpoints for malware", auto: "edr_scan", sla: "4h" },
      { phase: "Recovery", action: "Send targeted phishing awareness to affected users", auto: "send_awareness", sla: "24h" },
      { phase: "Post-Incident", action: "Add IOCs to threat intelligence blocklist", auto: "add_threat_intel", sla: "24h" },
      { phase: "Post-Incident", action: "Generate phishing incident summary", auto: "phishing_summary", sla: "72h" },
    ],
  },
  {
    type: "ddos",
    label: "DDoS Response",
    icon: "Activity",
    severity: "high",
    description: "NIST 800-61 DDoS mitigation and service restoration",
    steps: [
      { phase: "Detection & Analysis", action: "Confirm DDoS attack (traffic analysis)", auto: "confirm_ddos", sla: "0.5h" },
      { phase: "Detection & Analysis", action: "Identify attack vector (volumetric, protocol, app)", auto: "identify_vector", sla: "1h" },
      { phase: "Containment", action: "Activate DDoS protection (Shield/Cloudflare)", auto: "activate_ddos_protection", sla: "0.5h" },
      { phase: "Containment", action: "Enable rate limiting on affected services", auto: "enable_rate_limit", sla: "1h" },
      { phase: "Containment", action: "Block attacker IP ranges at edge", auto: "block_ips", sla: "1h" },
      { phase: "Containment", action: "Scale resources to absorb attack", auto: "scale_resources", sla: "1h" },
      { phase: "Eradication", action: "Work with ISP for upstream filtering", auto: "isp_filtering", sla: "4h" },
      { phase: "Recovery", action: "Monitor traffic and verify service restoration", auto: "verify_service", sla: "2h" },
      { phase: "Recovery", action: "Gradually remove mitigation rules", auto: "remove_mitigation", sla: "4h" },
      { phase: "Post-Incident", action: "Generate DDoS impact and mitigation report", auto: "ddos_report", sla: "72h" },
    ],
  },
  {
    type: "insider_threat",
    label: "Insider Threat Response",
    icon: "UserX",
    severity: "critical",
    description: "NIST 800-61 insider threat containment and investigation",
    steps: [
      { phase: "Detection & Analysis", action: "Confirm insider threat indicator (UEBA/alert)", auto: "confirm_insider", sla: "1h" },
      { phase: "Detection & Analysis", action: "Assess data access and exfiltration scope", auto: "assess_scope", sla: "4h" },
      { phase: "Containment", action: "Suspend user account and access", auto: "suspend_account", sla: "1h" },
      { phase: "Containment", action: "Revoke all sessions and API tokens", auto: "revoke_sessions", sla: "0.5h" },
      { phase: "Containment", action: "Quarantine user's endpoint(s)", auto: "quarantine_endpoint", sla: "1h" },
      { phase: "Containment", action: "Preserve forensic evidence (logs, files, emails)", auto: "preserve_evidence", sla: "4h" },
      { phase: "Containment", action: "Notify HR and legal counsel", auto: "notify_hr_legal", sla: "2h" },
      { phase: "Eradication", action: "Review all recent changes by the user", auto: "review_changes", sla: "8h" },
      { phase: "Eradication", action: "Identify and close any backdoor access", auto: "close_backdoors", sla: "4h" },
      { phase: "Recovery", action: "Restore any tampered data from backup", auto: "restore_backup", sla: "8h" },
      { phase: "Post-Incident", action: "Generate insider threat investigation report", auto: "insider_report", sla: "168h" },
      { phase: "Post-Incident", action: "Update access controls and monitoring rules", auto: "update_controls", sla: "168h" },
    ],
  },
  {
    type: "malware",
    label: "Malware Response",
    icon: "Bug",
    severity: "high",
    description: "NIST 800-61 malware containment and eradication",
    steps: [
      { phase: "Detection & Analysis", action: "Confirm malware detection (EDR/AV alert)", auto: "confirm_malware", sla: "0.5h" },
      { phase: "Detection & Analysis", action: "Identify malware type and IOCs", auto: "identify_malware", sla: "2h" },
      { phase: "Containment", action: "Isolate infected endpoint via EDR", auto: "isolate_endpoint", sla: "0.5h" },
      { phase: "Containment", action: "Block malware C2 and IOCs at network", auto: "block_c2", sla: "1h" },
      { phase: "Containment", action: "Identify other potentially infected hosts", auto: "identify_hosts", sla: "2h" },
      { phase: "Eradication", action: "Run full EDR scan on all endpoints", auto: "edr_full_scan", sla: "4h" },
      { phase: "Eradication", action: "Remove malware and persistence mechanisms", auto: "remove_malware", sla: "2h" },
      { phase: "Eradication", action: "Patch exploited vulnerability", auto: "create_patch_task", sla: "24h" },
      { phase: "Recovery", action: "Rebuild endpoint from clean image (if needed)", auto: "rebuild_endpoint", sla: "4h" },
      { phase: "Recovery", action: "Verify endpoint integrity before reconnecting", auto: "verify_integrity", sla: "2h" },
      { phase: "Post-Incident", action: "Add IOCs to threat intelligence blocklist", auto: "add_threat_intel", sla: "24h" },
      { phase: "Post-Incident", action: "Generate malware incident summary", auto: "malware_summary", sla: "72h" },
    ],
  },
  {
    type: "unauthorized_access",
    label: "Unauthorized Access Response",
    icon: "KeyRound",
    severity: "high",
    description: "NIST 800-61 unauthorized access containment and investigation",
    steps: [
      { phase: "Detection & Analysis", action: "Confirm unauthorized access attempt", auto: "confirm_access", sla: "1h" },
      { phase: "Detection & Analysis", action: "Identify source IP and attack vector", auto: "identify_source", sla: "2h" },
      { phase: "Containment", action: "Block source IP at firewall/WAF", auto: "block_ips", sla: "1h" },
      { phase: "Containment", action: "Revoke compromised credentials", auto: "revoke_credentials", sla: "1h" },
      { phase: "Containment", action: "Force password reset for affected accounts", auto: "force_password_reset", sla: "1h" },
      { phase: "Containment", action: "Enable MFA if not already enabled", auto: "enable_mfa", sla: "2h" },
      { phase: "Eradication", action: "Review access logs for lateral movement", auto: "review_logs", sla: "4h" },
      { phase: "Eradication", action: "Close exploited vulnerability", auto: "create_patch_task", sla: "24h" },
      { phase: "Recovery", action: "Verify no persistent backdoor access", auto: "verify_no_backdoor", sla: "4h" },
      { phase: "Post-Incident", action: "Generate unauthorized access report", auto: "access_report", sla: "72h" },
    ],
  },
];

export const playbookByType = (type) => IR_PLAYBOOKS.find((p) => p.type === type);

export const PLAYBOOK_TYPES = IR_PLAYBOOKS.map((p) => ({ type: p.type, label: p.label, severity: p.severity }));