/**
 * Pre-built GRC risk scenario library.
 * Each scenario is a template that can be imported into the tenant's Risk register.
 * Categorized by domain with suggested likelihood, impact, category, and treatment.
 */

export const riskScenarioCategories = [
  { value: "operational", label: "Operational" },
  { value: "technical", label: "Technical" },
  { value: "compliance", label: "Compliance" },
  { value: "financial", label: "Financial" },
  { value: "strategic", label: "Strategic" },
  { value: "reputational", label: "Reputational" },
  { value: "third_party", label: "Third-Party" },
];

export const riskScenarios = [
  {
    id: "rs-001",
    category: "technical",
    title: "Ransomware encryption of production systems",
    description: "Malicious actor deploys ransomware that encrypts critical production servers, causing extended downtime and potential data loss.",
    likelihood: 3,
    impact: 5,
    treatment: "mitigate",
    mitigation_plan: "Implement EDR/XDR on all endpoints, maintain immutable backups with 3-2-1 strategy, conduct quarterly tabletop exercises, enforce network segmentation.",
    tags: ["ransomware", "malware", "business_continuity"],
  },
  {
    id: "rs-002",
    category: "compliance",
    title: "POPIA/GDPR data breach notification failure",
    description: "Organization fails to notify the regulator within the required timeframe (72 hours for GDPR, reasonable time for POPIA) after discovering a personal data breach.",
    likelihood: 3,
    impact: 4,
    treatment: "mitigate",
    mitigation_plan: "Establish incident response playbook with mandatory regulator notification step, assign DPO as notification owner, conduct breach notification drills.",
    tags: ["privacy", "regulatory", "data_breach"],
  },
  {
    id: "rs-003",
    category: "third_party",
    title: "Critical SaaS vendor outage or data loss",
    description: "A critical SaaS provider (e.g. cloud hosting, CRM, identity provider) experiences extended outage or data loss, disrupting business operations.",
    likelihood: 2,
    impact: 4,
    treatment: "transfer",
    mitigation_plan: "Maintain vendor BCP/DR documentation, require SLA guarantees in contracts, implement multi-region failover where possible, maintain vendor risk assessments.",
    tags: ["vendor", "saas", "availability"],
  },
  {
    id: "rs-004",
    category: "operational",
    title: "Key personnel departure without knowledge transfer",
    description: "A key employee with critical institutional knowledge departs without adequate handover, creating operational gaps and single points of failure.",
    likelihood: 4,
    impact: 3,
    treatment: "mitigate",
    mitigation_plan: "Maintain documentation standards, implement cross-training programs, conduct knowledge transfer sessions before departures, enforce notice period handover checklists.",
    tags: ["human_resources", "knowledge_management"],
  },
  {
    id: "rs-005",
    category: "technical",
    title: "Misconfigured cloud storage exposing sensitive data",
    description: "Cloud storage bucket (S3, GCS, Azure Blob) is misconfigured with public access, exposing sensitive customer or employee data to the internet.",
    likelihood: 3,
    impact: 5,
    treatment: "mitigate",
    mitigation_plan: "Deploy CSPM continuous monitoring, enforce IaC with security policies, implement block-public-access at organization level, conduct quarterly access audits.",
    tags: ["cloud", "data_leak", "misconfiguration"],
  },
  {
    id: "rs-006",
    category: "compliance",
    title: "SOC 2 audit failure due to missing evidence",
    description: "Organization fails SOC 2 Type II audit due to insufficient or missing evidence for required controls, resulting in qualified opinion.",
    likelihood: 2,
    impact: 4,
    treatment: "mitigate",
    mitigation_plan: "Implement continuous evidence collection, maintain evidence calendar with expiry tracking, conduct pre-audit readiness assessments, assign control owners.",
    tags: ["soc2", "audit", "evidence"],
  },
  {
    id: "rs-007",
    category: "financial",
    title: "Fraudulent payment via business email compromise",
    description: "Attacker compromises an executive email account and sends fraudulent payment instructions to finance, resulting in unauthorized fund transfer.",
    likelihood: 3,
    impact: 4,
    treatment: "mitigate",
    mitigation_plan: "Enforce MFA on all email accounts, implement wire transfer verification protocols (call-back verification), conduct BEC awareness training, deploy email security gateway.",
    tags: ["fraud", "phishing", "financial_loss"],
  },
  {
    id: "rs-008",
    category: "technical",
    title: "Unpatched critical vulnerability exploitation",
    description: "A known critical CVE remains unpatched beyond SLA and is exploited by attackers, leading to system compromise.",
    likelihood: 4,
    impact: 4,
    treatment: "mitigate",
    mitigation_plan: "Implement vulnerability management program with SLA enforcement (critical: 7 days, high: 30 days), deploy automated patching where possible, maintain asset inventory.",
    tags: ["vulnerability", "patching", "exploitation"],
  },
  {
    id: "rs-009",
    category: "operational",
    title: "Insider threat — privilege abuse",
    description: "A privileged user intentionally or accidentally misuses access rights to exfiltrate data, modify records, or disrupt systems.",
    likelihood: 2,
    impact: 4,
    treatment: "mitigate",
    mitigation_plan: "Implement least-privilege access model, conduct quarterly access recertification, deploy DLP monitoring, enforce separation of duties, log and alert on privileged actions.",
    tags: ["insider_threat", "access_control", "privilege"],
  },
  {
    id: "rs-010",
    category: "compliance",
    title: "Regulatory change — new SADC data localization law",
    description: "A new SADC regulatory framework introduces data localization requirements that the organization's current architecture does not meet.",
    likelihood: 3,
    impact: 3,
    treatment: "mitigate",
    mitigation_plan: "Monitor regulatory changes via regulatory intelligence feed, maintain data flow maps, assess architecture against new requirements, engage legal counsel for gap analysis.",
    tags: ["regulatory_change", "data_localization", "sadc"],
  },
  {
    id: "rs-011",
    category: "reputational",
    title: "Public data breach disclosure — customer trust erosion",
    description: "A confirmed data breach becomes public, leading to customer churn, media scrutiny, and brand damage.",
    likelihood: 2,
    impact: 5,
    treatment: "mitigate",
    mitigation_plan: "Maintain breach response communication plan, engage PR firm on retainer, offer affected customers credit monitoring, demonstrate remediation transparency.",
    tags: ["reputation", "data_breach", "disclosure"],
  },
  {
    id: "rs-012",
    category: "technical",
    title: "Certificate expiry causing service outage",
    description: "An SSL/TLS certificate or API token expires unnoticed, causing service outages or integration failures.",
    likelihood: 3,
    impact: 3,
    treatment: "mitigate",
    mitigation_plan: "Maintain certificate inventory with automated expiry alerts, implement certificate management automation (ACME/Let's Encrypt), assign certificate owners.",
    tags: ["certificate", "outage", "ssl"],
  },
  {
    id: "rs-013",
    category: "third_party",
    title: "Sub-processor data handling non-compliance",
    description: "A vendor's sub-processor handles data in a way that violates the data processing agreement, creating compliance exposure.",
    likelihood: 2,
    impact: 3,
    treatment: "transfer",
    mitigation_plan: "Require sub-processor disclosure in contracts, include audit rights in DPAs, conduct annual vendor security reassessments, maintain sub-processor inventory.",
    tags: ["vendor", "sub-processor", "dpa"],
  },
  {
    id: "rs-014",
    category: "strategic",
    title: "M&A integration — inherited compliance debt",
    description: "An acquired company brings unmanaged compliance gaps and technical debt that the parent organization must remediate.",
    likelihood: 3,
    impact: 3,
    treatment: "mitigate",
    mitigation_plan: "Conduct pre-acquisition security due diligence, include compliance remediation in integration plan, assign integration compliance lead, set remediation timeline.",
    tags: ["ma", "integration", "compliance_debt"],
  },
  {
    id: "rs-015",
    category: "operational",
    title: "Disaster recovery plan not tested — recovery failure",
    description: "A disaster recovery plan exists but has never been tested, and actual failover fails due to undocumented dependencies or stale procedures.",
    likelihood: 3,
    impact: 5,
    treatment: "mitigate",
    mitigation_plan: "Conduct annual DR exercises (tabletop, simulation, full failover), maintain RTO/RPO documentation, update DR runbooks after each test, verify backup integrity.",
    tags: ["dr", "bcdr", "recovery"],
  },
];