// Shared SADC framework library — referenced by SADCFrameworks page and SADCExecutiveDashboard.
// Mirrors the SADC_LIBRARY constant in src/pages/SADCFrameworks.jsx.
export const SADC_LIBRARY = [
  { id: "popia", region: "South Africa", flag: "🇿🇦", name: "POPIA", full_name: "Protection of Personal Information Act", version: "2013 (Effective 2021)", category: "Data Privacy", authority: "Information Regulator (South Africa)", description: "South Africa's primary data protection legislation modelled on GDPR principles.", mandatory: true, controls_count: 48, key_requirements: ["Lawful processing conditions", "Data subject rights", "Security safeguards", "Breach notification (72h)", "PAIA alignment", "Trans-border data flows"], related_international: ["GDPR", "ISO 27001"], tags: ["privacy", "data protection", "south africa", "mandatory"] },
  { id: "fsra_bw", region: "Botswana", flag: "🇧🇼", name: "FSRA Cyber Rules", full_name: "Financial Services Regulatory Authority Cyber Rules", version: "2021", category: "Financial Services", authority: "FSRA Botswana", description: "Cybersecurity requirements for regulated financial entities in Botswana.", mandatory: true, controls_count: 34, key_requirements: ["Cyber risk governance", "Incident response plans", "Third-party risk management", "Penetration testing", "Business continuity", "SIEM implementation"], related_international: ["ISO 27001", "NIST CSF"], tags: ["financial services", "botswana", "cyber", "mandatory"] },
  { id: "dpa_zw", region: "Zimbabwe", flag: "🇿🇼", name: "Zimbabwe DPA", full_name: "Data Protection Act (Chapter 11:22)", version: "2021", category: "Data Privacy", authority: "Postal & Telecommunications Regulatory Authority (POTRAZ)", description: "Zimbabwe's data protection legislation.", mandatory: true, controls_count: 38, key_requirements: ["Data subject consent", "Registration with POTRAZ", "Data localisation requirements", "Security measures", "Cross-border transfer controls", "Breach reporting"], related_international: ["GDPR", "POPIA"], tags: ["privacy", "zimbabwe", "mandatory"] },
  { id: "cybersecurity_zw", region: "Zimbabwe", flag: "🇿🇼", name: "Zimbabwe Cyber Act", full_name: "Cyber & Data Protection Act", version: "2021", category: "Cybersecurity", authority: "Ministry of ICT (Zimbabwe)", description: "Comprehensive cybersecurity legislation in Zimbabwe.", mandatory: true, controls_count: 29, key_requirements: ["Critical infrastructure protection", "Cybercrime prevention", "Electronic evidence", "Computer emergency response", "Encryption standards"], related_international: ["Budapest Convention", "AU Convention"], tags: ["cybersecurity", "zimbabwe", "mandatory"] },
  { id: "cbk_kenya", region: "Kenya", flag: "🇰🇪", name: "CBK Cyber Guidelines", full_name: "Central Bank of Kenya Cybersecurity Guidelines", version: "2023", category: "Financial Services", authority: "Central Bank of Kenya", description: "Mandatory cybersecurity framework for CBK-regulated institutions.", mandatory: true, controls_count: 52, key_requirements: ["Board-level cyber governance", "Cyber risk appetite", "Vendor risk management", "Threat intelligence sharing", "24h incident reporting", "Annual cyber assessments"], related_international: ["ISO 27001", "PCI DSS", "NIST CSF"], tags: ["financial services", "kenya", "cyber", "mandatory"] },
  { id: "dpa_ke", region: "Kenya", flag: "🇰🇪", name: "Kenya DPA", full_name: "Data Protection Act (Kenya)", version: "2019", category: "Data Privacy", authority: "Office of the Data Protection Commissioner", description: "Kenya's data protection law.", mandatory: true, controls_count: 41, key_requirements: ["Data controller registration", "Privacy impact assessments", "Data subject rights (access, erasure)", "72h breach notification", "Privacy by design", "DPO appointment"], related_international: ["GDPR", "POPIA"], tags: ["privacy", "kenya", "mandatory"] },
  { id: "tan_dpa", region: "Tanzania", flag: "🇹🇿", name: "Tanzania DPA", full_name: "Tanzania Personal Data Protection Act", version: "2022", category: "Data Privacy", authority: "Tanzania Communications Regulatory Authority (TCRA)", description: "Tanzania's personal data protection law.", mandatory: true, controls_count: 35, key_requirements: ["Lawful basis for processing", "Data subject rights", "Security measures", "Breach notification", "Cross-border transfers", "TCRA registration"], related_international: ["GDPR", "AU Data Policy Framework"], tags: ["privacy", "tanzania", "mandatory"] },
  { id: "au_cybersecurity", region: "African Union", flag: "🌍", name: "AU Cyber Framework", full_name: "African Union Cybersecurity and Personal Data Protection Convention", version: "Malabo Convention 2014", category: "Cybersecurity", authority: "African Union Commission", description: "The primary pan-African legal framework for cybersecurity and data protection.", mandatory: false, controls_count: 45, key_requirements: ["Electronic transactions", "Personal data protection", "Cybersecurity measures", "Critical infrastructure", "Cybercrime legislation", "Regional cooperation"], related_international: ["Budapest Convention", "GDPR"], tags: ["africa", "cybersecurity", "privacy", "regional"] },
  { id: "sadc_finance", region: "SADC Region", flag: "🌍", name: "SADC Finance Protocol", full_name: "SADC Protocol on Finance & Investment — ICT Annex", version: "2006 (amended)", category: "Financial Services", authority: "SADC Secretariat", description: "Regional harmonisation framework for financial services regulation.", mandatory: false, controls_count: 22, key_requirements: ["Cross-border data governance", "Financial data standards", "AML/CFT integration", "Interoperability requirements"], related_international: ["FATF", "Basel III"], tags: ["finance", "sadc", "regional"] },
  { id: "bou_cyber", region: "Uganda", flag: "🇺🇬", name: "BOU Cyber Guidelines", full_name: "Bank of Uganda Cybersecurity Framework", version: "2022", category: "Financial Services", authority: "Bank of Uganda", description: "Cybersecurity risk management framework for BOU-licensed institutions.", mandatory: true, controls_count: 38, key_requirements: ["Cyber risk governance", "Vulnerability management", "Incident management", "Business continuity", "Staff awareness", "Regulatory reporting"], related_international: ["ISO 27001", "NIST CSF", "PCI DSS"], tags: ["financial services", "uganda", "cyber", "mandatory"] },
  { id: "mra_malawi", region: "Malawi", flag: "🇲🇼", name: "Malawi Cyber Act", full_name: "Electronic Transactions and Cybersecurity Act", version: "2016", category: "Cybersecurity", authority: "Malawi Communications Regulatory Authority (MACRA)", description: "Malawi's primary cybersecurity legislation.", mandatory: true, controls_count: 24, key_requirements: ["Electronic evidence admissibility", "Cybercrime offences", "Critical system protection", "Authentication standards"], related_international: ["Budapest Convention"], tags: ["cybersecurity", "malawi", "mandatory"] },
  { id: "zambia_cyber", region: "Zambia", flag: "🇿🇲", name: "Zambia Cyber Act", full_name: "Cyber Security and Cyber Crimes Act", version: "2021", category: "Cybersecurity", authority: "Zambia Information & Communications Technology Authority (ZICTA)", description: "Zambia's cybersecurity law addressing cyber threats and criminal offences.", mandatory: true, controls_count: 31, key_requirements: ["National CSIRT reporting", "Critical infrastructure protection", "Cybercrime offences", "Digital forensics", "Incident reporting"], related_international: ["AU Malabo Convention", "Budapest Convention"], tags: ["cybersecurity", "zambia", "mandatory"] },
];