// Shared Responsibility Matrix Library
// Based on the Cloud Shared Responsibility Model (AWS/CSA STAR) adapted for Base44 GRC platform.
// Segregates cloud provider (Base44 infrastructure) controls from tenant-managed configurations.

export const SHARED_RESPONSIBILITY_ITEMS = [
  // --- Provider-Managed (Base44 / Cloud Infrastructure) ---
  {
    item_id: "SRM-001",
    category: "infrastructure",
    control_area: "Physical Data Center Security",
    responsibility_model: "provider_managed",
    provider_responsibility: "Physical security of data centers including access controls, surveillance, environmental controls (fire, flood, power), and hardware disposal.",
    tenant_responsibility: "No tenant responsibility — physical infrastructure is fully managed by the cloud provider.",
    provider_controls: '[{"control":"Biometric facility access","status":"active"},{"control":"24/7 surveillance","status":"active"},{"control":"Redundant power (UPS + generator)","status":"active"}]',
    tenant_controls: '[]',
    framework_reference: "AWS Shared Responsibility Model — Infrastructure",
    tenant_status: "not_applicable",
  },
  {
    item_id: "SRM-002",
    category: "infrastructure",
    control_area: "Host OS & Platform Patching",
    responsibility_model: "provider_managed",
    provider_responsibility: "Patching and hardening of the host operating system, hypervisor, database engine, and Base44 platform runtime.",
    tenant_responsibility: "No tenant responsibility — platform infrastructure patching is fully automated by Base44.",
    provider_controls: '[{"control":"Automated OS patching","status":"active"},{"control":"Hypervisor security hardening","status":"active"},{"control":"Database engine updates","status":"active"}]',
    tenant_controls: '[]',
    framework_reference: "AWS Shared Responsibility Model — Infrastructure",
    tenant_status: "not_applicable",
  },
  {
    item_id: "SRM-003",
    category: "network_security",
    control_area: "Network Infrastructure & DDoS Protection",
    responsibility_model: "provider_managed",
    provider_responsibility: "Edge firewalls, DDoS mitigation, TLS termination, and network routing infrastructure protecting the platform.",
    tenant_responsibility: "No tenant responsibility — network infrastructure is managed by the cloud provider.",
    provider_controls: '[{"control":"Edge firewall rules","status":"active"},{"control":"DDoS protection layer","status":"active"},{"control":"TLS 1.3 enforcement","status":"active"}]',
    tenant_controls: '[]',
    framework_reference: "AWS Shared Responsibility Model — Infrastructure",
    tenant_status: "not_applicable",
  },
  {
    item_id: "SRM-004",
    category: "infrastructure",
    control_area: "Storage Encryption at Rest (Infrastructure)",
    responsibility_model: "provider_managed",
    provider_responsibility: "Transparent AES-256 encryption of all database volumes, object storage, and backups at the infrastructure level.",
    tenant_responsibility: "No tenant responsibility — infrastructure-level encryption is always on.",
    provider_controls: '[{"control":"AES-256 volume encryption","status":"active"},{"control":"Encrypted backups","status":"active"}]',
    tenant_controls: '[]',
    framework_reference: "ISO 27001 A.10.1.1",
    tenant_status: "not_applicable",
  },
  {
    item_id: "SRM-005",
    category: "infrastructure",
    control_area: "Platform Authentication Backend",
    responsibility_model: "provider_managed",
    provider_responsibility: "JWT issuance, session management, password hashing (bcrypt), OAuth/OIDC provider integration, and MFA enforcement at the platform level.",
    tenant_responsibility: "Configure which users belong to their tenant and assign roles — but cannot alter the cryptographic authentication mechanism.",
    provider_controls: '[{"control":"JWT signing & verification","status":"active"},{"control":"Bcrypt password hashing","status":"active"},{"control":"OAuth/OIDC integration","status":"active"}]',
    tenant_controls: '[{"control":"User role assignment","status":"configured"}]',
    framework_reference: "ISO 27001 A.9.2",
    tenant_status: "configured",
  },

  // --- Shared Responsibility ---
  {
    item_id: "SRM-006",
    category: "identity_access",
    control_area: "Identity & Access Management (IAM)",
    responsibility_model: "shared",
    provider_responsibility: "Provide the IAM framework, RBAC engine, SSO/SAML integration, and MFA enforcement capabilities.",
    tenant_responsibility: "Configure access policies, assign user roles, enforce least privilege, review access recertification campaigns, and manage user lifecycle (onboarding/offboarding).",
    provider_controls: '[{"control":"RBAC engine","status":"active"},{"control":"SSO/SAML support","status":"active"},{"control":"MFA enforcement","status":"active"}]',
    tenant_controls: '[{"control":"Access policy configuration","status":"partially_configured"},{"control":"Role assignment","status":"configured"},{"control":"Access recertification campaigns","status":"not_configured"}]',
    framework_reference: "ISO 27001 A.9 — Access Control",
    tenant_status: "partially_configured",
    gap_identified: true,
    gap_notes: "Access recertification campaigns not yet configured — quarterly reviews should be scheduled.",
  },
  {
    item_id: "SRM-007",
    category: "data_security",
    control_area: "Data Encryption (Application Layer)",
    responsibility_model: "shared",
    provider_responsibility: "Provide field-level encryption, evidence file hashing (SHA-256), and encrypted storage APIs.",
    tenant_responsibility: "Classify data by sensitivity, ensure evidence files are uploaded through secure channels, and manage retention policies.",
    provider_controls: '[{"control":"SHA-256 evidence hashing","status":"active"},{"control":"Encrypted storage API","status":"active"}]',
    tenant_controls: '[{"control":"Data classification tagging","status":"partially_configured"},{"control":"Retention policy configuration","status":"configured"}]',
    framework_reference: "ISO 27001 A.10 — Cryptography",
    tenant_status: "partially_configured",
    gap_identified: true,
    gap_notes: "Not all IT assets have data classification tags applied — review asset inventory.",
  },
  {
    item_id: "SRM-008",
    category: "compliance",
    control_area: "Compliance Framework Monitoring",
    responsibility_model: "shared",
    provider_responsibility: "Provide the framework library, automated control tests, compliance scoring engine, and audit trail.",
    tenant_responsibility: "Select applicable frameworks, map controls to requirements, collect evidence, and accept or remediate findings.",
    provider_controls: '[{"control":"Framework library (ISO, NIST, SADC)","status":"active"},{"control":"Automated control tests","status":"active"},{"control":"Compliance scoring engine","status":"active"}]',
    tenant_controls: '[{"control":"Framework selection","status":"configured"},{"control":"Control-to-requirement mapping","status":"partially_configured"},{"control":"Evidence collection","status":"partially_configured"}]',
    framework_reference: "ISO 27001, SOC 2, NIST CSF",
    tenant_status: "partially_configured",
  },
  {
    item_id: "SRM-009",
    category: "incident_response",
    control_area: "Incident Detection & Response",
    responsibility_model: "shared",
    provider_responsibility: "Provide anomaly detection, security alerts, incident logging, and automated alert routing (Slack/email).",
    tenant_responsibility: "Define incident response playbooks, assign incident owners, execute containment, and notify regulators where required.",
    provider_controls: '[{"control":"Anomaly detection engine","status":"active"},{"control":"Automated alert routing","status":"active"},{"control":"Incident timeline logging","status":"active"}]',
    tenant_controls: '[{"control":"IR playbook configuration","status":"partially_configured"},{"control":"Incident owner assignment","status":"configured"}]',
    framework_reference: "ISO 27001 A.16 — Incident Management",
    tenant_status: "partially_configured",
  },
  {
    item_id: "SRM-010",
    category: "monitoring_logging",
    control_area: "Monitoring & Audit Logging",
    responsibility_model: "shared",
    provider_responsibility: "Provide the immutable audit trail, activity logging infrastructure, and real-time monitoring dashboards.",
    tenant_responsibility: "Review audit logs, configure alert thresholds, and investigate flagged activities within their tenant.",
    provider_controls: '[{"control":"Immutable audit trail","status":"active"},{"control":"Real-time monitoring","status":"active"}]',
    tenant_controls: '[{"control":"Alert threshold configuration","status":"partially_configured"},{"control":"Audit log review","status":"not_configured"}]',
    framework_reference: "ISO 27001 A.12.4 — Logging",
    tenant_status: "partially_configured",
    gap_identified: true,
    gap_notes: "No scheduled audit log review process defined — assign a compliance officer to review weekly.",
  },
  {
    item_id: "SRM-011",
    category: "vulnerability_management",
    control_area: "Vulnerability & Patch Management",
    responsibility_model: "shared",
    provider_responsibility: "Patch platform infrastructure, scan for platform-level vulnerabilities, and provide security finding ingestion APIs.",
    tenant_responsibility: "Patch tenant-managed assets (endpoints, servers), ingest vulnerability scan results, and remediate findings within SLA.",
    provider_controls: '[{"control":"Platform vulnerability scanning","status":"active"},{"control":"Security finding ingestion API","status":"active"}]',
    tenant_controls: '[{"control":"Endpoint patching","status":"partially_configured"},{"control":"Vulnerability finding remediation","status":"partially_configured"}]',
    framework_reference: "ISO 27001 A.12.6 — Technical Vulnerability Management",
    tenant_status: "partially_configured",
  },

  // --- Tenant-Managed ---
  {
    item_id: "SRM-012",
    category: "data_classification",
    control_area: "Data Classification & Labeling",
    responsibility_model: "tenant_managed",
    provider_responsibility: "Provide data classification fields on assets, evidence, and policies.",
    tenant_responsibility: "Define data classification taxonomy (public, internal, confidential, restricted), tag all assets and data stores, and enforce handling rules per classification.",
    provider_controls: '[{"control":"Classification field on all entities","status":"active"}]',
    tenant_controls: '[{"control":"Classification taxonomy definition","status":"configured"},{"control":"Asset classification tagging","status":"partially_configured"},{"control":"Handling rules enforcement","status":"not_configured"}]',
    framework_reference: "ISO 27001 A.8.2 — Information Classification",
    tenant_status: "partially_configured",
    gap_identified: true,
    gap_notes: "Handling rules for restricted data not enforced — define DLP policies for restricted assets.",
  },
  {
    item_id: "SRM-013",
    category: "identity_access",
    control_area: "Access Policies & Role Assignments",
    responsibility_model: "tenant_managed",
    provider_responsibility: "Provide the RBAC framework and role definitions.",
    tenant_responsibility: "Assign users to roles, enforce least-privilege, conduct quarterly access reviews, and revoke access on role change or termination.",
    provider_controls: '[{"control":"RBAC framework","status":"active"}]',
    tenant_controls: '[{"control":"Role assignment","status":"configured"},{"control":"Least-privilege enforcement","status":"partially_configured"},{"control":"Quarterly access reviews","status":"not_configured"}]',
    framework_reference: "ISO 27001 A.9.4 — Access Control",
    tenant_status: "partially_configured",
    gap_identified: true,
    gap_notes: "Quarterly access recertification not scheduled — enable in Access Recertification module.",
  },
  {
    item_id: "SRM-014",
    category: "compliance",
    control_area: "Evidence Collection & Management",
    responsibility_model: "tenant_managed",
    provider_responsibility: "Provide evidence upload, hashing, versioning, and audit trail infrastructure.",
    tenant_responsibility: "Collect evidence on schedule, upload through the platform, ensure evidence freshness, and remediate missing/expired evidence.",
    provider_controls: '[{"control":"Evidence upload & hashing","status":"active"},{"control":"Version control","status":"active"}]',
    tenant_controls: '[{"control":"Evidence collection schedule","status":"partially_configured"},{"control":"Missing evidence remediation","status":"not_configured"}]',
    framework_reference: "SOC 2 CC4 — Evidence",
    tenant_status: "partially_configured",
  },
  {
    item_id: "SRM-015",
    category: "compliance",
    control_area: "Risk Acceptance & Treatment Decisions",
    responsibility_model: "tenant_managed",
    provider_responsibility: "Provide risk quantification (FAIR/ALE), risk appetite modeling, and treatment plan tracking.",
    tenant_responsibility: "Define risk appetite, accept or treat risks with formal sign-off, and ensure acceptance expiry reviews.",
    provider_controls: '[{"control":"FAIR risk quantification","status":"active"},{"control":"Risk appetite modeling","status":"active"}]',
    tenant_controls: '[{"control":"Risk appetite statement","status":"configured"},{"control":"Formal risk acceptance","status":"partially_configured"}]',
    framework_reference: "ISO 31000, COSO ERM",
    tenant_status: "partially_configured",
  },
  {
    item_id: "SRM-016",
    category: "compliance",
    control_area: "Policy Authoring & Approval",
    responsibility_model: "tenant_managed",
    provider_responsibility: "Provide policy templates, version control, and acknowledgment tracking.",
    tenant_responsibility: "Author organization-specific policies, route through approval workflows, and ensure employee acknowledgment.",
    provider_controls: '[{"control":"Policy template library","status":"active"},{"control":"Version control & acknowledgment","status":"active"}]',
    tenant_controls: '[{"control":"Policy authoring","status":"configured"},{"control":"Approval workflow","status":"partially_configured"}]',
    framework_reference: "ISO 27001 A.5 — Information Security Policies",
    tenant_status: "partially_configured",
  },
  {
    item_id: "SRM-017",
    category: "training_awareness",
    control_area: "Security Training & Awareness",
    responsibility_model: "tenant_managed",
    provider_responsibility: "Provide training modules, tracking, and enforcement gates.",
    tenant_responsibility: "Assign required training to employees, enforce completion deadlines, and track certification.",
    provider_controls: '[{"control":"Training module library","status":"active"},{"control":"Training gate enforcement","status":"active"}]',
    tenant_controls: '[{"control":"Training assignment","status":"partially_configured"},{"control":"Completion tracking","status":"partially_configured"}]',
    framework_reference: "ISO 27001 A.7.2.2 — Awareness",
    tenant_status: "partially_configured",
  },
  {
    item_id: "SRM-018",
    category: "backup_recovery",
    control_area: "Business Continuity & Disaster Recovery",
    responsibility_model: "tenant_managed",
    provider_responsibility: "Provide platform-level high availability, automated backups, and BCDR plan templates.",
    tenant_responsibility: "Define BCDR plans, set RTO/RPO targets, conduct tabletop exercises, and test failover procedures.",
    provider_controls: '[{"control":"Platform HA (multi-AZ)","status":"active"},{"control":"Automated backups","status":"active"}]',
    tenant_controls: '[{"control":"BCDR plan definition","status":"partially_configured"},{"control":"Tabletop exercises","status":"not_configured"}]',
    framework_reference: "ISO 27001 A.17 — Business Continuity",
    tenant_status: "partially_configured",
    gap_identified: true,
    gap_notes: "No tabletop exercises conducted — schedule at least one per quarter.",
  },
];

export const RESPONSIBILITY_MODEL_META = {
  provider_managed: {
    label: "Provider-Managed (Base44/Cloud)",
    color: "bg-blue-100 text-blue-700 border-blue-200",
    icon: "Cloud",
    description: "Fully managed by the cloud provider / Base44 infrastructure",
  },
  shared: {
    label: "Shared Responsibility",
    color: "bg-amber-100 text-amber-700 border-amber-200",
    icon: "Users",
    description: "Both provider and tenant have defined responsibilities",
  },
  tenant_managed: {
    label: "Tenant-Managed",
    color: "bg-emerald-100 text-emerald-700 border-emerald-200",
    icon: "Building2",
    description: "Fully managed by the tenant organization",
  },
};

export const CATEGORY_LABELS = {
  infrastructure: "Infrastructure",
  data_security: "Data Security",
  identity_access: "Identity & Access",
  network_security: "Network Security",
  compliance: "Compliance",
  incident_response: "Incident Response",
  data_classification: "Data Classification",
  encryption: "Encryption",
  backup_recovery: "Backup & Recovery",
  monitoring_logging: "Monitoring & Logging",
  vulnerability_management: "Vulnerability Management",
  training_awareness: "Training & Awareness",
};