export const SOAR_PLAYBOOKS = [
  {
    type: "ransomware_response",
    name: "Ransomware Isolation",
    description: "Automated ransomware containment: isolate host, preserve evidence, alert team, create remediation tasks",
    severity: "critical",
    trigger: "ransomware_detected",
    actions: [
      { type: "create_finding", title: "Ransomware Detection — Immediate Isolation Required", severity: "critical", description: "Ransomware activity detected. Host must be isolated immediately." },
      { type: "create_task", title: "Isolate affected host from network", priority: "critical", description: "Disconnect the affected host from all network segments to prevent lateral movement." },
      { type: "create_task", title: "Preserve forensic evidence (memory + disk image)", priority: "critical", description: "Capture volatile evidence before any remediation steps." },
      { type: "create_task", title: "Identify ransomware variant and check decryptors", priority: "high", description: "Use No More Ransom project to identify available decryptors." },
      { type: "create_task", title: "Notify law enforcement and regulatory authorities", priority: "high", description: "Report to relevant authorities within 72 hours per GDPR/POPIA." },
      { type: "send_slack_alert", message: "🚨 CRITICAL: Ransomware detected. Host isolation initiated. All SOC members must respond immediately." },
      { type: "create_evidence", title: "Ransomware Detection Evidence Pack", description: "Automated evidence preservation for forensic investigation and audit trail." },
    ],
  },
  {
    type: "data_exfiltration",
    name: "Data Exfiltration Response",
    description: "Detect and respond to data exfiltration: block user, preserve logs, alert DPO",
    severity: "critical",
    trigger: "dlp_data_staging_detected",
    actions: [
      { type: "create_finding", title: "Data Exfiltration Detected", severity: "critical", description: "Bulk data download and staging detected — potential exfiltration in progress." },
      { type: "create_task", title: "Disable user account and revoke all active sessions", priority: "critical", description: "Immediately disable the suspected user account across all systems." },
      { type: "create_task", title: "Block destination IP/domain at firewall", priority: "critical", description: "Block the exfiltration destination at the network perimeter." },
      { type: "create_task", title: "Notify Data Protection Officer (DPO)", priority: "high", description: "DPO must assess breach notification obligations under POPIA/GDPR within 72 hours." },
      { type: "create_evidence", title: "Data Exfiltration Evidence Pack", description: "Network flow logs, access logs, and DLP alerts preserved for investigation." },
      { type: "send_slack_alert", message: "🚨 CRITICAL: Data exfiltration detected. User account disabled. DPO notified." },
    ],
  },
  {
    type: "insider_threat",
    name: "Insider Threat Response",
    description: "Respond to insider threat indicators: monitor, restrict, investigate",
    severity: "high",
    trigger: "insider_threat_indicator",
    actions: [
      { type: "create_finding", title: "Insider Threat Indicator Detected", severity: "high", description: "Multiple insider threat indicators triggered for a single user." },
      { type: "create_task", title: "Restrict user access to sensitive systems", priority: "high", description: "Apply just-in-time access restrictions pending investigation." },
      { type: "create_task", title: "Conduct HR-coordinated investigation", priority: "high", description: "Coordinate with HR and legal for insider threat investigation." },
      { type: "create_evidence", title: "Insider Threat Evidence Pack", description: "Access patterns, anomaly flags, and behavioral indicators preserved." },
      { type: "send_slack_alert", message: "⚠️ HIGH: Insider threat indicators detected. Access restricted. Investigation initiated." },
    ],
  },
  {
    type: "credential_compromise",
    name: "Credential Compromise Response",
    description: "Respond to compromised credentials: reset passwords, revoke tokens, force MFA",
    severity: "critical",
    trigger: "credential_leak_detected",
    actions: [
      { type: "create_finding", title: "Credential Compromise Detected", severity: "critical", description: "Credentials found in public breach data or anomalous login patterns detected." },
      { type: "create_task", title: "Force password reset for all affected users", priority: "critical", description: "Immediately invalidate and require password reset." },
      { type: "create_task", title: "Revoke all OAuth tokens and active sessions", priority: "critical", description: "Invalidate all active sessions and refresh tokens." },
      { type: "create_task", title: "Enforce mandatory MFA re-enrollment", priority: "high", description: "Require all affected users to re-enroll MFA devices." },
      { type: "create_evidence", title: "Credential Compromise Evidence Pack", description: "Login logs, breach data correlation, and session tokens preserved." },
      { type: "send_slack_alert", message: "🚨 CRITICAL: Credential compromise detected. Password resets and token revocation initiated." },
    ],
  },
  {
    type: "malware_outbreak",
    name: "Malware Outbreak Response",
    description: "Respond to widespread malware detection: isolate, scan, remediate",
    severity: "high",
    trigger: "malware_outbreak_detected",
    actions: [
      { type: "create_finding", title: "Malware Outbreak Detected", severity: "high", description: "Multiple endpoints reporting malware detections simultaneously." },
      { type: "create_task", title: "Isolate all affected endpoints", priority: "critical", description: "Network-isolate all endpoints with active malware detections." },
      { type: "create_task", title: "Deploy emergency signature update to EDR", priority: "high", description: "Push latest threat signatures to all endpoints." },
      { type: "create_task", title: "Conduct full network scan for lateral movement", priority: "high", description: "Scan all network segments for indicators of lateral movement." },
      { type: "create_evidence", title: "Malware Outbreak Evidence Pack", description: "EDR detection logs, network flow data, and malware samples preserved." },
      { type: "send_slack_alert", message: "⚠️ HIGH: Malware outbreak detected across multiple endpoints. Isolation and scanning initiated." },
    ],
  },
  {
    type: "unauthorized_access",
    name: "Unauthorized Access Response",
    description: "Respond to unauthorized access attempts: block IP, alert SOC, create audit trail",
    severity: "high",
    trigger: "unauthorized_access_detected",
    actions: [
      { type: "create_finding", title: "Unauthorized Access Attempt", severity: "high", description: "Repeated unauthorized access attempts detected from external source." },
      { type: "create_task", title: "Block source IP at firewall/WAF", priority: "high", description: "Add source IP to blocklist at network perimeter and WAF." },
      { type: "create_task", title: "Review access logs for successful breaches", priority: "high", description: "Determine if any unauthorized access attempts succeeded." },
      { type: "create_evidence", title: "Unauthorized Access Evidence Pack", description: "Access logs, IP reputation data, and authentication failure logs preserved." },
      { type: "send_slack_alert", message: "⚠️ HIGH: Unauthorized access detected. Source IP blocked. SOC review initiated." },
    ],
  },
];