import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { sendGmail } from "../../shared/gmailSender.ts";

const SUPPORT_EMAIL = "support.certiguardgrc@gmail.com";

export default async function(req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json().catch(() => ({}));

    const {
      control_id, title, category, owner_name, severity,
      notes, framework_names, automation_status, last_tested,
    } = body;

    if (!title && !control_id) {
      return Response.json({ ok: false, error: "Missing control details" }, { status: 400 });
    }

    const sevColor = severity === "critical" ? "#EF4444"
      : severity === "high" ? "#F97316"
      : severity === "medium" ? "#F59E0B"
      : "#64748B";

    const subject = `🔴 Control Failure Alert: ${control_id || ""} — ${title || "Untitled"}`;

    const html = `
      <div style="font-family: Inter, Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: #1E293B; padding: 24px; border-radius: 8px 8px 0 0;">
          <h1 style="color: #EF4444; margin: 0; font-size: 20px;">⚠️ Control Status Changed to Failing</h1>
          <p style="color: #94A3B8; margin: 4px 0 0; font-size: 13px;">CertiGuard GRC — Automated Compliance Alert</p>
        </div>
        <div style="background: #F8FAFC; padding: 24px; border: 1px solid #E2E8F0; border-top: none; border-radius: 0 0 8px 8px;">
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr>
              <td style="padding: 8px 0; color: #64748B; font-weight: 600; width: 140px;">Control ID</td>
              <td style="padding: 8px 0; color: #1E293B; font-family: monospace;">${control_id || "—"}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #64748B; font-weight: 600;">Title</td>
              <td style="padding: 8px 0; color: #1E293B;">${title || "—"}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #64748B; font-weight: 600;">Category</td>
              <td style="padding: 8px 0; color: #1E293B;">${(category || "—").replace(/_/g, " ")}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #64748B; font-weight: 600;">Severity</td>
              <td style="padding: 8px 0; color: ${sevColor}; font-weight: 700; text-transform: uppercase;">${severity || "—"}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #64748B; font-weight: 600;">Owner</td>
              <td style="padding: 8px 0; color: #1E293B;">${owner_name || "Unassigned"}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #64748B; font-weight: 600;">Automation</td>
              <td style="padding: 8px 0; color: #1E293B;">${(automation_status || "—").replace(/_/g, " ")}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #64748B; font-weight: 600;">Last Tested</td>
              <td style="padding: 8px 0; color: #1E293B;">${last_tested || "—"}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #64748B; font-weight: 600;">Frameworks</td>
              <td style="padding: 8px 0; color: #1E293B;">${Array.isArray(framework_names) ? framework_names.join(", ") : framework_names || "—"}</td>
            </tr>
          </table>
          ${notes
            ? `<div style="margin-top: 16px; padding: 12px; background: #FEF2F2; border-radius: 6px; border-left: 4px solid #EF4444;"><strong style="color: #991B1B;">Notes:</strong> <span style="color: #1E293B;">${notes}</span></div>`
            : ""}
          <div style="margin-top: 20px; padding: 14px; background: #FFF7ED; border-radius: 6px; border-left: 4px solid #F59E0B;">
            <strong style="color: #92400E;">Action Required:</strong>
            <span style="color: #1E293B;"> This control has regressed to a failing state. Please review and initiate remediation immediately to maintain audit readiness.</span>
          </div>
          <p style="margin-top: 24px; color: #94A3B8; font-size: 11px;">Alert generated by CertiGuard GRC · ${new Date().toISOString()}</p>
        </div>
      </div>
    `;

    const result = await sendGmail(base44, SUPPORT_EMAIL, subject, html);

    console.log("Control failure alert sent:", JSON.stringify({
      control_id, title, to: SUPPORT_EMAIL, messageId: result?.id,
    }));

    return Response.json({ ok: true, messageId: result?.id, to: SUPPORT_EMAIL });
  } catch (error) {
    console.error("sendControlFailureAlert error:", error?.message || error);
    return Response.json({ ok: false, error: error?.message || "Failed to send alert" }, { status: 500 });
  }
}