import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const sr = base44.asServiceRole;
    const body = await req.json().catch(() => ({}));
    const { control_id } = body;

    if (!control_id) {
      return Response.json({ error: "control_id is required" }, { status: 400 });
    }

    // Fetch the control and its linked evidence
    const control = await sr.entities.Control.get(control_id).catch(() => null);
    if (!control) {
      return Response.json({ error: "Control not found" }, { status: 404 });
    }

    // Get linked evidence for context
    const allEvidence = await sr.entities.Evidence.list("-created_date", 200).catch(() => []);
    const linkedEvidence = (allEvidence || []).filter((e) => e.control_id === control_id);

    // Build context for the LLM
    const context = {
      control_id: control.control_id,
      title: control.title,
      description: control.description,
      category: control.category,
      severity: control.severity,
      status: control.status,
      owner: control.owner_name,
      automation_status: control.automation_status,
      evidence_count: control.evidence_count || linkedEvidence.length,
      evidence_items: linkedEvidence.slice(0, 5).map((e) => ({
        title: e.title,
        type: e.type,
        status: e.status,
        collected_date: e.collected_date,
      })),
    };

    // Generate remediation plan using LLM
    const llmRes = await base44.integrations.Core.InvokeLLM({
      prompt: `You are a senior GRC remediation advisor. A security control has failed and needs a structured remediation project plan.

Control details (JSON):
${JSON.stringify(context, null, 2)}

Generate a comprehensive remediation plan with:
1. Root cause analysis — why this control likely failed
2. 3-5 specific remediation tasks with clear actions, suggested owner roles, priorities, and estimated days to complete
3. Success criteria — how to verify the control is back to passing
4. Overall estimated timeline (total days)

Be specific and actionable. Each task should be independently assignable and trackable.`,
      response_json_schema: {
        type: "object",
        properties: {
          root_cause: { type: "string", description: "Likely root cause of the control failure" },
          severity_assessment: { type: "string", description: "Assessment of remediation urgency" },
          tasks: {
            type: "array",
            items: {
              type: "object",
              properties: {
                title: { type: "string", description: "Short actionable task title" },
                description: { type: "string", description: "Detailed task description with specific actions" },
                suggested_owner_role: { type: "string", description: "Suggested role for the task owner (e.g. Security Engineer, IT Admin, Compliance Officer)" },
                priority: { type: "string", enum: ["critical", "high", "medium", "low"], description: "Task priority" },
                estimated_days: { type: "number", description: "Estimated days to complete this task" },
                dependencies: { type: "string", description: "Any dependencies on other tasks (by title)" },
              },
              required: ["title", "description", "suggested_owner_role", "priority", "estimated_days"],
            },
          },
          estimated_total_days: { type: "number", description: "Total estimated days for the full remediation" },
          success_criteria: { type: "string", description: "How to verify the control is back to passing" },
        },
        required: ["root_cause", "tasks", "estimated_total_days", "success_criteria"],
      },
    });

    const plan = llmRes || { root_cause: "Unable to generate analysis", tasks: [], estimated_total_days: 0, success_criteria: "" };

    // Create ComplianceTask records for each remediation task
    const createdTasks = [];
    const today = new Date();
    let cumulativeDays = 0;

    for (const task of (plan.tasks || [])) {
      cumulativeDays += task.estimated_days || 3;
      const dueDate = new Date(today.getTime() + cumulativeDays * 86400000).toISOString().slice(0, 10);

      const created = await sr.entities.ComplianceTask.create({
        tenant_id: control.tenant_id,
        title: task.title,
        description: task.description,
        type: "remediation",
        status: "todo",
        priority: task.priority || "high",
        assignee_name: control.owner_name || "",
        assignee_id: control.owner_id || "",
        due_date: dueDate,
        related_control_id: control.id,
        notes: `Auto-generated by AI Remediation Plan. Owner role: ${task.suggested_owner_role}. Dependencies: ${task.dependencies || "none"}. Success criteria: ${plan.success_criteria || "n/a"}`,
      }).catch((e) => null);

      if (created) {
        createdTasks.push({
          id: created.id,
          title: task.title,
          priority: task.priority,
          due_date: dueDate,
          suggested_owner_role: task.suggested_owner_role,
          estimated_days: task.estimated_days,
        });
      }
    }

    return Response.json({
      ok: true,
      control_id: control.id,
      control_title: control.title,
      root_cause: plan.root_cause,
      severity_assessment: plan.severity_assessment || "",
      tasks: createdTasks,
      estimated_total_days: plan.estimated_total_days,
      success_criteria: plan.success_criteria,
      generated_at: new Date().toISOString(),
    });
  } catch (error) {
    console.error("generateRemediationPlan error:", error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});